//! The implementation of every trait the generated server declares.
//!
//! Generated by firestone from the same OpenAPI document as the server, so the two
//! cannot disagree about an operation id, a model name or a response variant.
//! Do not edit: change the resource files and regenerate.
//!
//! Each handler does the same three things - pull the request apart, enforce the
//! rules the schema declares, then hand off to the [`Backend`](crate::backend::Backend).
//! Only the last of those is yours to write.

use async_trait::async_trait;
use axum_extra::extract::CookieJar;
use axum_extra::extract::Host;
use http::Method;
use serde_json::Value;

use addressbook_api::apis;
use addressbook_api::models;

use crate::error::from_json;
use crate::error::to_json;
use crate::error::Error;
use crate::resolver::validate_request;
use crate::resolver::validate_subject;
use crate::Api;

#[async_trait]
impl apis::addressbook::Addressbook<Error> for Api {
    /// DELETE /addressbook/{address_key}/addrtype
    async fn addressbook_address_key_addrtype_delete(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyAddrtypeDeletePathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyAddrtypeDeleteResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyAddrtypeDeleteResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let removed = current
            .get("addrtype")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook addrtype", key))?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .remove("addrtype");
        validate_subject(self, "delete", "addressbook", &updated, Some(&current)).await?;
        self.backend.replace("addressbook", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(removed)?))
    }

    /// GET /addressbook/{address_key}/addrtype
    async fn addressbook_address_key_addrtype_get(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyAddrtypeGetPathParams,
        _query_params: &models::AddressbookAddressKeyAddrtypeGetQueryParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyAddrtypeGetResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyAddrtypeGetResponse as Response;

        let key = &path_params.address_key;
        let found = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let value = found
            .get("addrtype")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook addrtype", key))?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }

    /// HEAD /addressbook/{address_key}/addrtype
    async fn addressbook_address_key_addrtype_head(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _path_params: &models::AddressbookAddressKeyAddrtypeHeadPathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyAddrtypeHeadResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyAddrtypeHeadResponse as Response;

        Ok(Response::Status200_DefaultHEADResponse)
    }

    /// PUT /addressbook/{address_key}/addrtype
    async fn addressbook_address_key_addrtype_put(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyAddrtypePutPathParams,
        body: &String,
    ) -> Result<apis::addressbook::AddressbookAddressKeyAddrtypePutResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyAddrtypePutResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let value = to_json(body)?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .insert("addrtype".to_string(), value.clone());
        // The rules are written against the whole resource, so they are given the
        // resource as it will be rather than the attribute on its own.
        validate_subject(self, "put", "addressbook", &updated, Some(&current)).await?;
        self.backend.replace("addressbook", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }

    /// DELETE /addressbook/{address_key}/city
    async fn addressbook_address_key_city_delete(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyCityDeletePathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyCityDeleteResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyCityDeleteResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let removed = current
            .get("city")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook city", key))?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .remove("city");
        validate_subject(self, "delete", "addressbook", &updated, Some(&current)).await?;
        self.backend.replace("addressbook", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(removed)?))
    }

    /// GET /addressbook/{address_key}/city
    async fn addressbook_address_key_city_get(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyCityGetPathParams,
        _query_params: &models::AddressbookAddressKeyCityGetQueryParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyCityGetResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyCityGetResponse as Response;

        let key = &path_params.address_key;
        let found = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let value = found
            .get("city")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook city", key))?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }

    /// HEAD /addressbook/{address_key}/city
    async fn addressbook_address_key_city_head(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _path_params: &models::AddressbookAddressKeyCityHeadPathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyCityHeadResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyCityHeadResponse as Response;

        Ok(Response::Status200_DefaultHEADResponse)
    }

    /// PUT /addressbook/{address_key}/city
    async fn addressbook_address_key_city_put(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyCityPutPathParams,
        body: &String,
    ) -> Result<apis::addressbook::AddressbookAddressKeyCityPutResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyCityPutResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let value = to_json(body)?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .insert("city".to_string(), value.clone());
        // The rules are written against the whole resource, so they are given the
        // resource as it will be rather than the attribute on its own.
        validate_subject(self, "put", "addressbook", &updated, Some(&current)).await?;
        self.backend.replace("addressbook", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }

    /// DELETE /addressbook/{address_key}/country
    async fn addressbook_address_key_country_delete(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyCountryDeletePathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyCountryDeleteResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyCountryDeleteResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let removed = current
            .get("country")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook country", key))?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .remove("country");
        validate_subject(self, "delete", "addressbook", &updated, Some(&current)).await?;
        self.backend.replace("addressbook", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(removed)?))
    }

    /// GET /addressbook/{address_key}/country
    async fn addressbook_address_key_country_get(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyCountryGetPathParams,
        _query_params: &models::AddressbookAddressKeyCountryGetQueryParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyCountryGetResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyCountryGetResponse as Response;

        let key = &path_params.address_key;
        let found = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let value = found
            .get("country")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook country", key))?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }

    /// HEAD /addressbook/{address_key}/country
    async fn addressbook_address_key_country_head(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _path_params: &models::AddressbookAddressKeyCountryHeadPathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyCountryHeadResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyCountryHeadResponse as Response;

        Ok(Response::Status200_DefaultHEADResponse)
    }

    /// PUT /addressbook/{address_key}/country
    async fn addressbook_address_key_country_put(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyCountryPutPathParams,
        body: &String,
    ) -> Result<apis::addressbook::AddressbookAddressKeyCountryPutResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyCountryPutResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let value = to_json(body)?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .insert("country".to_string(), value.clone());
        // The rules are written against the whole resource, so they are given the
        // resource as it will be rather than the attribute on its own.
        validate_subject(self, "put", "addressbook", &updated, Some(&current)).await?;
        self.backend.replace("addressbook", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }

    /// DELETE /addressbook/{address_key}
    async fn addressbook_address_key_delete(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyDeletePathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyDeleteResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyDeleteResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        // A delete has no body, so the rules see the resource that is about to go.
        validate_request(self, "delete", "addressbook", None, Some(&current)).await?;
        self.backend.delete("addressbook", key).await?;
        tracing::info!(resource = "addressbook", key, "deleted");

        Ok(Response::Status200_ResponseForOK(from_json(current)?))
    }

    /// GET /addressbook/{address_key}
    async fn addressbook_address_key_get(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyGetPathParams,
        _query_params: &models::AddressbookAddressKeyGetQueryParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyGetResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyGetResponse as Response;

        let key = &path_params.address_key;
        let found = self.backend.get("addressbook", key).await?;

        Ok(Response::Status200_ResponseForOK(from_json(
            found.ok_or_else(|| Error::not_found("addressbook", key))?,
        )?))
    }

    /// HEAD /addressbook/{address_key}
    async fn addressbook_address_key_head(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _path_params: &models::AddressbookAddressKeyHeadPathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyHeadResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyHeadResponse as Response;

        Ok(Response::Status200_DefaultHEADResponse)
    }

    /// DELETE /addressbook/{address_key}/is_valid
    async fn addressbook_address_key_is_valid_delete(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyIsValidDeletePathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyIsValidDeleteResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyIsValidDeleteResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let removed = current
            .get("is_valid")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook is_valid", key))?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .remove("is_valid");
        validate_subject(self, "delete", "addressbook", &updated, Some(&current)).await?;
        self.backend.replace("addressbook", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(removed)?))
    }

    /// GET /addressbook/{address_key}/is_valid
    async fn addressbook_address_key_is_valid_get(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyIsValidGetPathParams,
        _query_params: &models::AddressbookAddressKeyIsValidGetQueryParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyIsValidGetResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyIsValidGetResponse as Response;

        let key = &path_params.address_key;
        let found = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let value = found
            .get("is_valid")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook is_valid", key))?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }

    /// HEAD /addressbook/{address_key}/is_valid
    async fn addressbook_address_key_is_valid_head(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _path_params: &models::AddressbookAddressKeyIsValidHeadPathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyIsValidHeadResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyIsValidHeadResponse as Response;

        Ok(Response::Status200_DefaultHEADResponse)
    }

    /// PUT /addressbook/{address_key}/is_valid
    async fn addressbook_address_key_is_valid_put(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyIsValidPutPathParams,
        body: &bool,
    ) -> Result<apis::addressbook::AddressbookAddressKeyIsValidPutResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyIsValidPutResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let value = to_json(body)?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .insert("is_valid".to_string(), value.clone());
        // The rules are written against the whole resource, so they are given the
        // resource as it will be rather than the attribute on its own.
        validate_subject(self, "put", "addressbook", &updated, Some(&current)).await?;
        self.backend.replace("addressbook", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }

    /// DELETE /addressbook/{address_key}/people
    async fn addressbook_address_key_people_delete(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyPeopleDeletePathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyPeopleDeleteResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyPeopleDeleteResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let removed = current
            .get("people")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook people", key))?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .remove("people");
        validate_subject(self, "delete", "addressbook", &updated, Some(&current)).await?;
        self.backend.replace("addressbook", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(removed)?))
    }

    /// GET /addressbook/{address_key}/people
    async fn addressbook_address_key_people_get(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyPeopleGetPathParams,
        _query_params: &models::AddressbookAddressKeyPeopleGetQueryParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyPeopleGetResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyPeopleGetResponse as Response;

        let key = &path_params.address_key;
        let found = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let value = found
            .get("people")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook people", key))?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }

    /// HEAD /addressbook/{address_key}/people
    async fn addressbook_address_key_people_head(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _path_params: &models::AddressbookAddressKeyPeopleHeadPathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyPeopleHeadResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyPeopleHeadResponse as Response;

        Ok(Response::Status200_DefaultHEADResponse)
    }

    /// PUT /addressbook/{address_key}/people
    async fn addressbook_address_key_people_put(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyPeoplePutPathParams,
        body: &Vec<String>,
    ) -> Result<apis::addressbook::AddressbookAddressKeyPeoplePutResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyPeoplePutResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let value = to_json(body)?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .insert("people".to_string(), value.clone());
        // The rules are written against the whole resource, so they are given the
        // resource as it will be rather than the attribute on its own.
        validate_subject(self, "put", "addressbook", &updated, Some(&current)).await?;
        self.backend.replace("addressbook", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }

    /// DELETE /addressbook/{address_key}/person
    async fn addressbook_address_key_person_delete(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyPersonDeletePathParams,
        _query_params: &models::AddressbookAddressKeyPersonDeleteQueryParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyPersonDeleteResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyPersonDeleteResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let removed = current
            .get("person")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook person", key))?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .remove("person");
        validate_subject(self, "delete", "addressbook", &updated, Some(&current)).await?;
        self.backend.replace("addressbook", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(removed)?))
    }

    /// GET /addressbook/{address_key}/person
    async fn addressbook_address_key_person_get(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyPersonGetPathParams,
        _query_params: &models::AddressbookAddressKeyPersonGetQueryParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyPersonGetResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyPersonGetResponse as Response;

        let key = &path_params.address_key;
        let found = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let value = found
            .get("person")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook person", key))?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }

    /// HEAD /addressbook/{address_key}/person
    async fn addressbook_address_key_person_head(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _path_params: &models::AddressbookAddressKeyPersonHeadPathParams,
        _query_params: &models::AddressbookAddressKeyPersonHeadQueryParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyPersonHeadResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyPersonHeadResponse as Response;

        Ok(Response::Status200_DefaultHEADResponse)
    }

    /// PATCH /addressbook/{address_key}/person
    async fn addressbook_address_key_person_patch(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _path_params: &models::AddressbookAddressKeyPersonPatchPathParams,
        _query_params: &models::AddressbookAddressKeyPersonPatchQueryParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyPersonPatchResponse, Error> {
        // Firestone does not generate a body for this operation: the document
        // declares no request body or no success response, or the method means
        // something a replace would get wrong. Implement it by hand if you need it.
        Err(Error::NotImplemented(
            "PATCH /addressbook/{address_key}/person is not generated; implement it by hand".into(),
        ))
    }

    /// POST /addressbook/{address_key}/person
    async fn addressbook_address_key_person_post(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _path_params: &models::AddressbookAddressKeyPersonPostPathParams,
        _query_params: &models::AddressbookAddressKeyPersonPostQueryParams,
        _body: &models::CreatePerson,
    ) -> Result<apis::addressbook::AddressbookAddressKeyPersonPostResponse, Error> {
        // Firestone does not generate a body for this operation: the document
        // declares no request body or no success response, or the method means
        // something a replace would get wrong. Implement it by hand if you need it.
        Err(Error::NotImplemented(
            "POST /addressbook/{address_key}/person is not generated; implement it by hand".into(),
        ))
    }

    /// PUT /addressbook/{address_key}
    async fn addressbook_address_key_put(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyPutPathParams,
        body: &models::UpdateAddressbook,
    ) -> Result<apis::addressbook::AddressbookAddressKeyPutResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyPutResponse as Response;

        let key = &path_params.address_key;
        let body = to_json(body)?;
        // Rules comparing against the current state need it, whether or not the
        // backend would have.
        let current = self.backend.get("addressbook", key).await?;
        validate_request(self, "put", "addressbook", Some(&body), current.as_ref()).await?;
        let stored = self.backend.replace("addressbook", key, body).await?;

        Ok(Response::Status200_ResponseForOK(from_json(stored)?))
    }

    /// DELETE /addressbook/{address_key}/state
    async fn addressbook_address_key_state_delete(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyStateDeletePathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyStateDeleteResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyStateDeleteResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let removed = current
            .get("state")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook state", key))?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .remove("state");
        validate_subject(self, "delete", "addressbook", &updated, Some(&current)).await?;
        self.backend.replace("addressbook", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(removed)?))
    }

    /// GET /addressbook/{address_key}/state
    async fn addressbook_address_key_state_get(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyStateGetPathParams,
        _query_params: &models::AddressbookAddressKeyStateGetQueryParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyStateGetResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyStateGetResponse as Response;

        let key = &path_params.address_key;
        let found = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let value = found
            .get("state")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook state", key))?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }

    /// HEAD /addressbook/{address_key}/state
    async fn addressbook_address_key_state_head(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _path_params: &models::AddressbookAddressKeyStateHeadPathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyStateHeadResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyStateHeadResponse as Response;

        Ok(Response::Status200_DefaultHEADResponse)
    }

    /// PUT /addressbook/{address_key}/state
    async fn addressbook_address_key_state_put(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyStatePutPathParams,
        body: &String,
    ) -> Result<apis::addressbook::AddressbookAddressKeyStatePutResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyStatePutResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let value = to_json(body)?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .insert("state".to_string(), value.clone());
        // The rules are written against the whole resource, so they are given the
        // resource as it will be rather than the attribute on its own.
        validate_subject(self, "put", "addressbook", &updated, Some(&current)).await?;
        self.backend.replace("addressbook", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }

    /// DELETE /addressbook/{address_key}/street
    async fn addressbook_address_key_street_delete(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyStreetDeletePathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyStreetDeleteResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyStreetDeleteResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let removed = current
            .get("street")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook street", key))?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .remove("street");
        validate_subject(self, "delete", "addressbook", &updated, Some(&current)).await?;
        self.backend.replace("addressbook", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(removed)?))
    }

    /// GET /addressbook/{address_key}/street
    async fn addressbook_address_key_street_get(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyStreetGetPathParams,
        _query_params: &models::AddressbookAddressKeyStreetGetQueryParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyStreetGetResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyStreetGetResponse as Response;

        let key = &path_params.address_key;
        let found = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let value = found
            .get("street")
            .cloned()
            .ok_or_else(|| Error::not_found("addressbook street", key))?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }

    /// HEAD /addressbook/{address_key}/street
    async fn addressbook_address_key_street_head(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _path_params: &models::AddressbookAddressKeyStreetHeadPathParams,
    ) -> Result<apis::addressbook::AddressbookAddressKeyStreetHeadResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyStreetHeadResponse as Response;

        Ok(Response::Status200_DefaultHEADResponse)
    }

    /// PUT /addressbook/{address_key}/street
    async fn addressbook_address_key_street_put(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::AddressbookAddressKeyStreetPutPathParams,
        body: &String,
    ) -> Result<apis::addressbook::AddressbookAddressKeyStreetPutResponse, Error> {
        use apis::addressbook::AddressbookAddressKeyStreetPutResponse as Response;

        let key = &path_params.address_key;
        let current = self
            .backend
            .get("addressbook", key)
            .await?
            .ok_or_else(|| Error::not_found("addressbook", key))?;
        let value = to_json(body)?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .insert("street".to_string(), value.clone());
        // The rules are written against the whole resource, so they are given the
        // resource as it will be rather than the attribute on its own.
        validate_subject(self, "put", "addressbook", &updated, Some(&current)).await?;
        self.backend.replace("addressbook", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }

    /// GET /addressbook
    async fn addressbook_get(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _query_params: &models::AddressbookGetQueryParams,
    ) -> Result<apis::addressbook::AddressbookGetResponse, Error> {
        use apis::addressbook::AddressbookGetResponse as Response;

        let items = self.backend.list("addressbook").await?;

        Ok(Response::Status200_ResponseForOK(from_json(Value::Array(
            items,
        ))?))
    }

    /// POST /addressbook
    async fn addressbook_post(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _query_params: &models::AddressbookPostQueryParams,
        body: &models::CreateAddressbook,
    ) -> Result<apis::addressbook::AddressbookPostResponse, Error> {
        use apis::addressbook::AddressbookPostResponse as Response;

        let body = to_json(body)?;
        validate_request(self, "post", "addressbook", Some(&body), None).await?;
        let (key, mut created) = self.backend.create("addressbook", body).await?;
        tracing::info!(resource = "addressbook", key, "created");

        // The backend mints the key, so the caller is told what it was: without it
        // there is no way to GET, PUT or DELETE what was just created.
        if let Some(object) = created.as_object_mut() {
            object.insert("address_key".to_string(), Value::String(key));
        }

        Ok(Response::Status201_ResponseForCREATED(from_json(created)?))
    }
}

#[async_trait]
impl apis::persons::Persons<Error> for Api {
    type Claims = crate::auth::Claims;

    /// GET /persons
    async fn persons_get(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _query_params: &models::PersonsGetQueryParams,
    ) -> Result<apis::persons::PersonsGetResponse, Error> {
        use apis::persons::PersonsGetResponse as Response;

        let items = self.backend.list("persons").await?;

        Ok(Response::Status200_ResponseForOK(from_json(Value::Array(
            items,
        ))?))
    }

    /// POST /persons
    async fn persons_post(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _claims: &Self::Claims,
        _query_params: &models::PersonsPostQueryParams,
        body: &models::CreatePerson,
    ) -> Result<apis::persons::PersonsPostResponse, Error> {
        use apis::persons::PersonsPostResponse as Response;

        let body = to_json(body)?;
        validate_request(self, "post", "persons", Some(&body), None).await?;
        let (key, mut created) = self.backend.create("persons", body).await?;
        tracing::info!(resource = "persons", key, "created");

        // The backend mints the key, so the caller is told what it was: without it
        // there is no way to GET, PUT or DELETE what was just created.
        if let Some(object) = created.as_object_mut() {
            object.insert("uuid".to_string(), Value::String(key));
        }

        Ok(Response::Status201_ResponseForCREATED(from_json(created)?))
    }

    /// DELETE /persons/{uuid}
    async fn persons_uuid_delete(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _claims: &Self::Claims,
        path_params: &models::PersonsUuidDeletePathParams,
    ) -> Result<apis::persons::PersonsUuidDeleteResponse, Error> {
        use apis::persons::PersonsUuidDeleteResponse as Response;

        let key = &path_params.uuid;
        let current = self
            .backend
            .get("persons", key)
            .await?
            .ok_or_else(|| Error::not_found("persons", key))?;
        // A delete has no body, so the rules see the resource that is about to go.
        validate_request(self, "delete", "persons", None, Some(&current)).await?;
        self.backend.delete("persons", key).await?;
        tracing::info!(resource = "persons", key, "deleted");

        Ok(Response::Status200_ResponseForOK(from_json(current)?))
    }

    /// GET /persons/{uuid}
    async fn persons_uuid_get(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::PersonsUuidGetPathParams,
        _query_params: &models::PersonsUuidGetQueryParams,
    ) -> Result<apis::persons::PersonsUuidGetResponse, Error> {
        use apis::persons::PersonsUuidGetResponse as Response;

        let key = &path_params.uuid;
        let found = self.backend.get("persons", key).await?;

        Ok(Response::Status200_ResponseForOK(from_json(
            found.ok_or_else(|| Error::not_found("persons", key))?,
        )?))
    }

    /// HEAD /persons/{uuid}
    async fn persons_uuid_head(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _path_params: &models::PersonsUuidHeadPathParams,
    ) -> Result<apis::persons::PersonsUuidHeadResponse, Error> {
        use apis::persons::PersonsUuidHeadResponse as Response;

        Ok(Response::Status200_DefaultHEADResponse)
    }

    /// PUT /persons/{uuid}
    async fn persons_uuid_put(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _claims: &Self::Claims,
        path_params: &models::PersonsUuidPutPathParams,
        body: &models::UpdatePerson,
    ) -> Result<apis::persons::PersonsUuidPutResponse, Error> {
        use apis::persons::PersonsUuidPutResponse as Response;

        let key = &path_params.uuid;
        let body = to_json(body)?;
        // Rules comparing against the current state need it, whether or not the
        // backend would have.
        let current = self.backend.get("persons", key).await?;
        validate_request(self, "put", "persons", Some(&body), current.as_ref()).await?;
        let stored = self.backend.replace("persons", key, body).await?;

        Ok(Response::Status200_ResponseForOK(from_json(stored)?))
    }
}

#[async_trait]
impl apis::postal_codes::PostalCodes<Error> for Api {
    type Claims = crate::auth::Claims;

    /// GET /postal_codes
    async fn postal_codes_get(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _query_params: &models::PostalCodesGetQueryParams,
    ) -> Result<apis::postal_codes::PostalCodesGetResponse, Error> {
        use apis::postal_codes::PostalCodesGetResponse as Response;

        let items = self.backend.list("postal_codes").await?;

        Ok(Response::Status200_ResponseForOK(from_json(Value::Array(
            items,
        ))?))
    }

    /// POST /postal_codes
    async fn postal_codes_post(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _claims: &Self::Claims,
        _query_params: &models::PostalCodesPostQueryParams,
        body: &models::CreatePostalCode,
    ) -> Result<apis::postal_codes::PostalCodesPostResponse, Error> {
        use apis::postal_codes::PostalCodesPostResponse as Response;

        let body = to_json(body)?;
        let (key, mut created) = self.backend.create("postal_codes", body).await?;
        tracing::info!(resource = "postal_codes", key, "created");

        // The backend mints the key, so the caller is told what it was: without it
        // there is no way to GET, PUT or DELETE what was just created.
        if let Some(object) = created.as_object_mut() {
            object.insert("uuid".to_string(), Value::String(key));
        }

        Ok(Response::Status201_ResponseForCREATED(from_json(created)?))
    }

    /// DELETE /postal_codes/{uuid}
    async fn postal_codes_uuid_delete(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _claims: &Self::Claims,
        path_params: &models::PostalCodesUuidDeletePathParams,
    ) -> Result<apis::postal_codes::PostalCodesUuidDeleteResponse, Error> {
        use apis::postal_codes::PostalCodesUuidDeleteResponse as Response;

        let key = &path_params.uuid;
        let current = self
            .backend
            .get("postal_codes", key)
            .await?
            .ok_or_else(|| Error::not_found("postal_codes", key))?;
        self.backend.delete("postal_codes", key).await?;
        tracing::info!(resource = "postal_codes", key, "deleted");

        Ok(Response::Status200_ResponseForOK(from_json(current)?))
    }

    /// GET /postal_codes/{uuid}
    async fn postal_codes_uuid_get(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::PostalCodesUuidGetPathParams,
        _query_params: &models::PostalCodesUuidGetQueryParams,
    ) -> Result<apis::postal_codes::PostalCodesUuidGetResponse, Error> {
        use apis::postal_codes::PostalCodesUuidGetResponse as Response;

        let key = &path_params.uuid;
        let found = self.backend.get("postal_codes", key).await?;

        Ok(Response::Status200_ResponseForOK(from_json(
            found.ok_or_else(|| Error::not_found("postal_codes", key))?,
        )?))
    }

    /// HEAD /postal_codes/{uuid}
    async fn postal_codes_uuid_head(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _path_params: &models::PostalCodesUuidHeadPathParams,
    ) -> Result<apis::postal_codes::PostalCodesUuidHeadResponse, Error> {
        use apis::postal_codes::PostalCodesUuidHeadResponse as Response;

        Ok(Response::Status200_DefaultHEADResponse)
    }

    /// DELETE /postal_codes/{uuid}/name
    async fn postal_codes_uuid_name_delete(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        _claims: &Self::Claims,
        path_params: &models::PostalCodesUuidNameDeletePathParams,
    ) -> Result<apis::postal_codes::PostalCodesUuidNameDeleteResponse, Error> {
        use apis::postal_codes::PostalCodesUuidNameDeleteResponse as Response;

        let key = &path_params.uuid;
        let current = self
            .backend
            .get("postal_codes", key)
            .await?
            .ok_or_else(|| Error::not_found("postal_codes", key))?;
        let removed = current
            .get("name")
            .cloned()
            .ok_or_else(|| Error::not_found("postal_codes name", key))?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| Error::Internal("the stored resource is not an object".into()))?
            .remove("name");
        self.backend.replace("postal_codes", key, updated).await?;

        Ok(Response::Status200_ResponseForOK(from_json(removed)?))
    }

    /// GET /postal_codes/{uuid}/name
    async fn postal_codes_uuid_name_get(
        &self,
        _method: &Method,
        _host: &Host,
        _cookies: &CookieJar,
        path_params: &models::PostalCodesUuidNameGetPathParams,
        _query_params: &models::PostalCodesUuidNameGetQueryParams,
    ) -> Result<apis::postal_codes::PostalCodesUuidNameGetResponse, Error> {
        use apis::postal_codes::PostalCodesUuidNameGetResponse as Response;

        let key = &path_params.uuid;
        let found = self
            .backend
            .get("postal_codes", key)
            .await?
            .ok_or_else(|| Error::not_found("postal_codes", key))?;
        let value = found
            .get("name")
            .cloned()
            .ok_or_else(|| Error::not_found("postal_codes name", key))?;

        Ok(Response::Status200_ResponseForOK(from_json(value)?))
    }
}
