//! Example person and addressbook API
//!
//! Example person and addressbook API
//!
//! The router, models, per-operation authentication and request validation are the
//! sibling `addressbook_api` crate, generated by openapi-generator from the OpenAPI
//! document firestone produced. This crate implements the traits that crate
//! declares, so the only thing left to write is a [`backend::Backend`].

pub mod auth;
pub mod backend;
pub mod error;
pub mod handlers;
pub mod resolver;
pub mod validation;

use std::sync::Arc;

pub use error::Error;

/// The implementation the generated server is built around.
///
/// Handed to `addressbook_api::server::new`, which routes every operation in the
/// OpenAPI document to one of its methods.
#[derive(Clone)]
pub struct Api {
    /// Where the data lives.
    pub backend: Arc<dyn backend::Backend>,
    /// The bearer tokens the secured operations accept.
    pub tokens: Vec<String>,
}

impl Api {
    /// Build the implementation around a backend, reading API_TOKENS for the
    /// credentials the secured operations accept.
    pub fn new(backend: Arc<dyn backend::Backend>) -> Self {
        let tokens = std::env::var("API_TOKENS").unwrap_or_default();

        Api::with_tokens(
            backend,
            tokens
                .split(',')
                .map(str::trim)
                .filter(|token| !token.is_empty())
                .map(str::to_string),
        )
    }

    /// The same, with the tokens given rather than read from the environment, so a
    /// test or an embedding binary can supply its own.
    pub fn with_tokens(
        backend: Arc<dyn backend::Backend>,
        tokens: impl IntoIterator<Item = String>,
    ) -> Self {
        Api {
            backend,
            tokens: tokens.into_iter().collect(),
        }
    }
}

impl AsRef<Api> for Api {
    fn as_ref(&self) -> &Api {
        self
    }
}

/// Render anything the typed responses cannot as an RFC 9457 problem document.
///
/// The generated server calls this for an error a handler returned, which is how a
/// 404, or a rule the OpenAPI document did not declare a response for, still
/// reaches the caller with a sensible status.
#[async_trait::async_trait]
impl addressbook_api::apis::ErrorHandler<Error> for Api {
    async fn handle_error(
        &self,
        _method: &::http::Method,
        _host: &axum_extra::extract::Host,
        _cookies: &axum_extra::extract::CookieJar,
        error: Error,
    ) -> Result<axum::response::Response, http::StatusCode> {
        tracing::info!("{error}");

        Ok(axum::response::IntoResponse::into_response(error))
    }
}

/// Build the router for every operation in the OpenAPI document.
pub fn router(api: Api) -> axum::Router {
    addressbook_api::server::new(api)
}
