# coding: utf-8

# flake8: noqa

"""
Example person and addressbook API

Example person and addressbook API

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from addressbook.client.api.addressbook_api import AddressbookApi
from addressbook.client.api.persons_api import PersonsApi
from addressbook.client.api.postal_codes_api import PostalCodesApi

# import ApiClient
from addressbook.client.api_response import ApiResponse
from addressbook.client.api_client import ApiClient
from addressbook.client.configuration import Configuration
from addressbook.client.exceptions import OpenApiException
from addressbook.client.exceptions import ApiTypeError
from addressbook.client.exceptions import ApiValueError
from addressbook.client.exceptions import ApiKeyError
from addressbook.client.exceptions import ApiAttributeError
from addressbook.client.exceptions import ApiException

# import models into sdk package
from addressbook.client.models.addressbook import Addressbook
from addressbook.client.models.create_addressbook import CreateAddressbook
from addressbook.client.models.create_person import CreatePerson
from addressbook.client.models.create_postal_code import CreatePostalCode
from addressbook.client.models.person import Person
from addressbook.client.models.postal_code import PostalCode
from addressbook.client.models.update_addressbook import UpdateAddressbook
from addressbook.client.models.update_person import UpdatePerson
