// Auto-generated CLI module - generated by firestone
use clap::{Parser, Subcommand};
use serde_json;

#[derive(clap::ValueEnum, Clone, Debug)]
pub enum AddrtypeEnum {
Work,
Home,
}

impl AsRef<str> for AddrtypeEnum {
    fn as_ref(&self) -> &str {
        match self {
            AddrtypeEnum::Work => "work",
            AddrtypeEnum::Home => "home",
            }
    }
}
/// Shared connection parameters passed to every handler.
/// Each handler builds its own typed client-crate Configuration from these.
/// `base_url` is `None` means "use the client crate's compiled-in default".
pub struct ApiContext {
    pub base_url: Option<String>,
    pub api_key: Option<String>,
}

#[derive(Subcommand, Debug)]
pub enum AddressbookCommands {
    /// Create a new address in this addressbook, a new address key will be created.
    Create(CreateArgs),
    /// List all addresses in this addressbook.
    List(ListArgs),
    /// Delete an address from this addressbook.
    Delete(DeleteArgs),
    /// Get a specific address from this addressbook.
    Get(GetArgs),
    /// Update an existing address in this addressbook, with the given address key.
    Update(UpdateArgs),
    }

#[derive(Parser, Debug)]
pub struct CreateArgs {
/// A unique identifier for an addressbook entry.
    #[arg(long)]
    pub address_key: Option<String>,
    /// The address type, e.g. work or home
    #[arg(long, value_enum)]
    pub addrtype: AddrtypeEnum,
    /// The city of this address
    #[arg(long)]
    pub city: String,
    /// The country of this address
    #[arg(long)]
    pub country: String,
    /// Address is valid or not
    #[arg(long, action = clap::ArgAction::SetTrue)]
    pub is_valid: Option<bool>,
    /// Limit the number of responses back
    #[arg(long)]
    pub limit: Option<i64>,
    /// The offset to start returning resources
    #[arg(long)]
    pub offset: Option<i64>,
    /// A list of people's names living there
    #[arg(long)]
    pub people: Option<Vec<String>>,
    /// This is a person object that lives at this address.
    #[arg(long)]
    pub person: Option<String>,
    /// The state of this address
    #[arg(long)]
    pub state: String,
    /// The street and civic number of this address
    #[arg(long)]
    pub street: String,
    }

#[derive(Parser, Debug)]
pub struct ListArgs {
/// Filter by city name
    #[arg(long)]
    pub city: Option<String>,
    /// Limit the number of responses back
    #[arg(long)]
    pub limit: Option<i64>,
    /// The offset to start returning resources
    #[arg(long)]
    pub offset: Option<i64>,
    }

#[derive(Parser, Debug)]
pub struct DeleteArgs {
/// 
    pub address_key: String,
    }

#[derive(Parser, Debug)]
pub struct GetArgs {
/// 
    pub address_key: String,
    /// Filter by city name
    #[arg(long)]
    pub city: Option<String>,
    }

#[derive(Parser, Debug)]
pub struct UpdateArgs {
/// A unique identifier for an addressbook entry.
    pub address_key: String,
    /// The address type, e.g. work or home
    #[arg(long, value_enum)]
    pub addrtype: Option<AddrtypeEnum>,
    /// The city of this address
    #[arg(long)]
    pub city: Option<String>,
    /// The country of this address
    #[arg(long)]
    pub country: Option<String>,
    /// Address is valid or not
    #[arg(long, action = clap::ArgAction::SetTrue)]
    pub is_valid: Option<bool>,
    /// A list of people's names living there
    #[arg(long)]
    pub people: Option<Vec<String>>,
    /// This is a person object that lives at this address.
    #[arg(long)]
    pub person: Option<String>,
    /// The state of this address
    #[arg(long)]
    pub state: Option<String>,
    /// The street and civic number of this address
    #[arg(long)]
    pub street: Option<String>,
    }

pub async fn handle_addressbook_command(
    ctx: &ApiContext,
    cmd: &AddressbookCommands,
) -> Result<(), Box<dyn std::error::Error>> {
    match cmd {
AddressbookCommands::Create(args) => {
            handle_addressbook_post(ctx, args).await
        },
AddressbookCommands::List(args) => {
            handle_addressbook_get(ctx, args).await
        },
AddressbookCommands::Delete(args) => {
            handle_addressbook_address_key_delete(ctx, args).await
        },
AddressbookCommands::Get(args) => {
            handle_addressbook_address_key_get(ctx, args).await
        },
AddressbookCommands::Update(args) => {
            handle_addressbook_address_key_put(ctx, args).await
        },
}
}

pub async fn handle_addressbook_post(
    ctx: &ApiContext,
    args: &CreateArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build request body for create operation
    let req_body = crate::models::CreateAddressbook {
        address_key: args.address_key.as_ref().map(|s| Some(serde_json::Value::String(s.clone()))),
        addrtype: match args.addrtype {
            AddrtypeEnum::Work => crate::models::create_addressbook::Addrtype::Work,
            AddrtypeEnum::Home => crate::models::create_addressbook::Addrtype::Home,
            },
        city: args.city.clone(),
        country: args.country.clone(),
        is_valid: args.is_valid,
        people: args.people.clone(),
        person: args.person.as_ref().and_then(|s| serde_json::from_str::<crate::models::Person>(s).ok()).map(|p| Box::new(p)),
        state: args.state.clone(),
        street: args.street.clone(),
        };
    // Build query parameters for create operation
    let limit_param = args.limit.map(|v| v as i32);
    let offset_param = args.offset.map(|v| v as i32);
    let resp = crate::apis::addressbook_api::addressbook_post(&config, req_body, limit_param, offset_param).await?;
    let json_output = serde_json::to_string_pretty(&resp)?;
    println!("{}", json_output);
    Ok(())
}

pub async fn handle_addressbook_get(
    ctx: &ApiContext,
    args: &ListArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build query parameters - openapi-generator functions take individual Option parameters
    let city_param = args.city.as_ref().map(|s| s.as_str());
    let limit_param = args.limit.map(|v| v as i32);
    let offset_param = args.offset.map(|v| v as i32);
    let resp = crate::apis::addressbook_api::addressbook_get(&config, city_param, limit_param, offset_param).await?;
    let json_output = serde_json::to_string_pretty(&resp)?;
    println!("{}", json_output);
    Ok(())
}

pub async fn handle_addressbook_address_key_delete(
    ctx: &ApiContext,
    args: &DeleteArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build query parameters for instance operations
    // DELETE operations may return empty responses (204 No Content)
    let resp_result = crate::apis::addressbook_api::addressbook_address_key_delete(&config, &args.address_key).await;
    match resp_result {
        Ok(data) => {
            let json_output = serde_json::to_string_pretty(&data)?;
            println!("{}", json_output);
        },
        Err(crate::apis::Error::Serde(e)) => {
            let error_msg = e.to_string();
            if error_msg.contains("content type") || error_msg.contains("application/octet-stream") || error_msg.contains("cannot be converted") {
                println!("{}", r#"{"status": "deleted"}"#);
            } else {
                return Err(Box::new(e));
            }
        },
        Err(e) => return Err(Box::new(e)),
    }
    Ok(())
}

pub async fn handle_addressbook_address_key_get(
    ctx: &ApiContext,
    args: &GetArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build query parameters for instance operations
    let city_param = args.city.as_ref().map(|s| s.as_str());
    let resp = crate::apis::addressbook_api::addressbook_address_key_get(&config, &args.address_key, city_param).await?;
    let json_output = serde_json::to_string_pretty(&resp)?;
    println!("{}", json_output);
    Ok(())
}

pub async fn handle_addressbook_address_key_put(
    ctx: &ApiContext,
    args: &UpdateArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build request body for update operation
    let req_body = crate::models::UpdateAddressbook {
        address_key: None,
        addrtype: args.addrtype.as_ref().map(|e| match e {
            AddrtypeEnum::Work => crate::models::update_addressbook::Addrtype::Work,
            AddrtypeEnum::Home => crate::models::update_addressbook::Addrtype::Home,
            }),
        city: args.city.clone(),
        country: args.country.clone(),
        is_valid: args.is_valid,
        people: args.people.clone(),
        person: args.person.as_ref().and_then(|s| serde_json::from_str::<crate::models::Person>(s).ok()).map(|p| Box::new(p)),
        state: args.state.clone(),
        street: args.street.clone(),
        };

    let resp = crate::apis::addressbook_api::addressbook_address_key_put(&config, req_body, &args.address_key).await?;
    let json_output = serde_json::to_string_pretty(&resp)?;
    println!("{}", json_output);
    Ok(())
}

