// Auto-generated CLI module - generated by firestone
use clap::{Parser, Subcommand};
use serde_json;

#[derive(clap::ValueEnum, Clone, Debug)]
pub enum PriorityEnum {
High,
Medium,
Low,
}

impl AsRef<str> for PriorityEnum {
    fn as_ref(&self) -> &str {
        match self {
            PriorityEnum::High => "high",
            PriorityEnum::Medium => "medium",
            PriorityEnum::Low => "low",
            }
    }
}
#[derive(clap::ValueEnum, Clone, Debug)]
pub enum StatusEnum {
Active,
Inactive,
Archived,
}

impl AsRef<str> for StatusEnum {
    fn as_ref(&self) -> &str {
        match self {
            StatusEnum::Active => "active",
            StatusEnum::Inactive => "inactive",
            StatusEnum::Archived => "archived",
            }
    }
}
#[derive(clap::ValueEnum, Clone, Debug)]
pub enum TypeEnum {
Personal,
Business,
Emergency,
}

impl AsRef<str> for TypeEnum {
    fn as_ref(&self) -> &str {
        match self {
            TypeEnum::Personal => "personal",
            TypeEnum::Business => "business",
            TypeEnum::Emergency => "emergency",
            }
    }
}
/// Shared connection parameters passed to every handler.
/// Each handler builds its own typed client-crate Configuration from these.
/// `base_url` is `None` means "use the client crate's compiled-in default".
pub struct ApiContext {
    pub base_url: Option<String>,
    pub api_key: Option<String>,
}

#[derive(Subcommand, Debug)]
pub enum ContactsCommands {
    /// Create a new contact in this collection
    Create(CreateArgs),
    /// List all contacts in this collection
    List(ListArgs),
    /// Delete this contact from the collection
    Delete(DeleteArgs),
    /// Get a specific contact from this collection
    Get(GetArgs),
    }

#[derive(Parser, Debug)]
pub struct CreateArgs {
/// Contact categories (array of enums)
    #[arg(long)]
    pub categories: Vec<String>,
    /// The unique ID for this contact
    #[arg(long)]
    pub contact_id: String,
    /// Contact email address
    #[arg(long)]
    pub email: Option<String>,
    /// Limit the number of responses back
    #[arg(long)]
    pub limit: Option<i64>,
    /// The contact's name
    #[arg(long)]
    pub name: String,
    /// Optional notes (array of strings, not enums)
    #[arg(long)]
    pub notes: Option<Vec<String>>,
    /// The offset to start returning resources
    #[arg(long)]
    pub offset: Option<i64>,
    /// Contact priority level (required enum)
    #[arg(long, value_enum)]
    pub priority: PriorityEnum,
    /// The status of the contact (optional enum with default)
    #[arg(long, value_enum)]
    #[arg(default_value = "active")]
    pub status: StatusEnum,
    /// The contact type (optional enum, tests Rust keyword escaping)
    #[arg(long, value_enum)]
    pub r#type: Option<TypeEnum>,
    }

#[derive(Parser, Debug)]
pub struct ListArgs {
/// Limit the number of responses back
    #[arg(long)]
    pub limit: Option<i64>,
    /// The offset to start returning resources
    #[arg(long)]
    pub offset: Option<i64>,
    }

#[derive(Parser, Debug)]
pub struct DeleteArgs {
/// 
    pub contact_id: String,
    }

#[derive(Parser, Debug)]
pub struct GetArgs {
/// 
    pub contact_id: String,
    }

pub async fn handle_contacts_command(
    ctx: &ApiContext,
    cmd: &ContactsCommands,
) -> Result<(), Box<dyn std::error::Error>> {
    match cmd {
ContactsCommands::Create(args) => {
            handle_contacts_post(ctx, args).await
        },
ContactsCommands::List(args) => {
            handle_contacts_get(ctx, args).await
        },
ContactsCommands::Delete(args) => {
            handle_contacts_contact_id_delete(ctx, args).await
        },
ContactsCommands::Get(args) => {
            handle_contacts_contact_id_get(ctx, args).await
        },
}
}

pub async fn handle_contacts_post(
    ctx: &ApiContext,
    args: &CreateArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build request body for create operation
    let req_body = crate::models::CreateContact {
        categories: args.categories.iter().map(|s| match s.to_lowercase().as_str() {
            "family" => crate::models::create_contact::Categories::Family,
            "friend" => crate::models::create_contact::Categories::Friend,
            "colleague" => crate::models::create_contact::Categories::Colleague,
            "vendor" => crate::models::create_contact::Categories::Vendor,
            _ => panic!("Invalid enum value for categories: {}", s),
        }).collect(),
        contact_id: Some(serde_json::Value::String(args.contact_id.clone())),
        email: args.email.clone(),
        name: args.name.clone(),
        notes: args.notes.clone(),
        priority: match args.priority {
            PriorityEnum::High => crate::models::create_contact::Priority::High,
            PriorityEnum::Medium => crate::models::create_contact::Priority::Medium,
            PriorityEnum::Low => crate::models::create_contact::Priority::Low,
            },
        status: Some(match args.status {
            StatusEnum::Active => crate::models::create_contact::Status::Active,
            StatusEnum::Inactive => crate::models::create_contact::Status::Inactive,
            StatusEnum::Archived => crate::models::create_contact::Status::Archived,
            }),
        r#type: args.r#type.as_ref().map(|e| match e {
            TypeEnum::Personal => crate::models::create_contact::Type::Personal,
            TypeEnum::Business => crate::models::create_contact::Type::Business,
            TypeEnum::Emergency => crate::models::create_contact::Type::Emergency,
            }),
        };
    // Build query parameters for create operation
    let limit_param = args.limit.map(|v| v as i32);
    let offset_param = args.offset.map(|v| v as i32);
    let resp = crate::apis::contacts_api::contacts_post(&config, req_body, limit_param, offset_param).await?;
    let json_output = serde_json::to_string_pretty(&resp)?;
    println!("{}", json_output);
    Ok(())
}

pub async fn handle_contacts_get(
    ctx: &ApiContext,
    args: &ListArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build query parameters - openapi-generator functions take individual Option parameters
    let limit_param = args.limit.map(|v| v as i32);
    let offset_param = args.offset.map(|v| v as i32);
    let resp = crate::apis::contacts_api::contacts_get(&config, limit_param, offset_param).await?;
    let json_output = serde_json::to_string_pretty(&resp)?;
    println!("{}", json_output);
    Ok(())
}

pub async fn handle_contacts_contact_id_delete(
    ctx: &ApiContext,
    args: &DeleteArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build query parameters for instance operations
    // DELETE operations may return empty responses (204 No Content)
    let resp_result = crate::apis::contacts_api::contacts_contact_id_delete(&config, &args.contact_id).await;
    match resp_result {
        Ok(data) => {
            let json_output = serde_json::to_string_pretty(&data)?;
            println!("{}", json_output);
        },
        Err(crate::apis::Error::Serde(e)) => {
            let error_msg = e.to_string();
            if error_msg.contains("content type") || error_msg.contains("application/octet-stream") || error_msg.contains("cannot be converted") {
                println!("{}", r#"{"status": "deleted"}"#);
            } else {
                return Err(Box::new(e));
            }
        },
        Err(e) => return Err(Box::new(e)),
    }
    Ok(())
}

pub async fn handle_contacts_contact_id_get(
    ctx: &ApiContext,
    args: &GetArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build query parameters for instance operations
    let resp = crate::apis::contacts_api::contacts_contact_id_get(&config, &args.contact_id).await?;
    let json_output = serde_json::to_string_pretty(&resp)?;
    println!("{}", json_output);
    Ok(())
}

