// Auto-generated CLI module - generated by firestone
use clap::{Parser, Subcommand};
use serde_json;

/// Shared connection parameters passed to every handler.
/// Each handler builds its own typed client-crate Configuration from these.
/// `base_url` is `None` means "use the client crate's compiled-in default".
pub struct ApiContext {
    pub base_url: Option<String>,
    pub api_key: Option<String>,
}

#[derive(Subcommand, Debug)]
pub enum PersonsCommands {
    /// Create a new person in this collection, a new UUID key will be created
    Create(CreateArgs),
    /// List all persons in this collection
    List(ListArgs),
    /// Delete operation for persons
    Delete(DeleteArgs),
    /// Get a specific person from this collection
    Get(GetArgs),
    /// Put a new person in this collection, with the given UUId key
    Update(UpdateArgs),
    }

#[derive(Parser, Debug)]
pub struct CreateArgs {
/// The person's age
    #[arg(long)]
    pub age: Option<i64>,
    /// The person's first name
    #[arg(long)]
    pub first_name: Option<String>,
    /// The person's hobbies
    #[arg(long)]
    pub hobbies: Option<Vec<String>>,
    /// The person's last name
    #[arg(long)]
    pub last_name: Option<String>,
    /// Limit the number of responses back
    #[arg(long)]
    pub limit: Option<i64>,
    /// The offset to start returning resources
    #[arg(long)]
    pub offset: Option<i64>,
    /// The person's timezone (e.g. UTC, America/New_York)
    #[arg(long)]
    #[arg(default_value = "UTC")]
    pub timezone: String,
    /// A UUID associated to this person
    #[arg(long)]
    pub uuid: Option<String>,
    }

#[derive(Parser, Debug)]
pub struct ListArgs {
/// Filter by last name
    #[arg(long)]
    pub last_name: Option<String>,
    /// Limit the number of responses back
    #[arg(long)]
    pub limit: Option<i64>,
    /// The offset to start returning resources
    #[arg(long)]
    pub offset: Option<i64>,
    }

#[derive(Parser, Debug)]
pub struct DeleteArgs {
/// 
    pub uuid: String,
    }

#[derive(Parser, Debug)]
pub struct GetArgs {
/// Filter by last name
    #[arg(long)]
    pub last_name: Option<String>,
    /// 
    pub uuid: String,
    }

#[derive(Parser, Debug)]
pub struct UpdateArgs {
/// The person's age
    #[arg(long)]
    pub age: Option<i64>,
    /// The person's first name
    #[arg(long)]
    pub first_name: Option<String>,
    /// The person's hobbies
    #[arg(long)]
    pub hobbies: Option<Vec<String>>,
    /// The person's last name
    #[arg(long)]
    pub last_name: Option<String>,
    /// The person's timezone (e.g. UTC, America/New_York)
    #[arg(long)]
    pub timezone: Option<String>,
    /// A UUID associated to this person
    pub uuid: String,
    }

pub async fn handle_persons_command(
    ctx: &ApiContext,
    cmd: &PersonsCommands,
) -> Result<(), Box<dyn std::error::Error>> {
    match cmd {
PersonsCommands::Create(args) => {
            handle_persons_post(ctx, args).await
        },
PersonsCommands::List(args) => {
            handle_persons_get(ctx, args).await
        },
PersonsCommands::Delete(args) => {
            handle_persons_uuid_delete(ctx, args).await
        },
PersonsCommands::Get(args) => {
            handle_persons_uuid_get(ctx, args).await
        },
PersonsCommands::Update(args) => {
            handle_persons_uuid_put(ctx, args).await
        },
}
}

pub async fn handle_persons_post(
    ctx: &ApiContext,
    args: &CreateArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build request body for create operation
    let req_body = crate::models::CreatePerson {
        age: args.age.map(|v| v as i32),
        first_name: args.first_name.clone(),
        hobbies: args.hobbies.clone(),
        last_name: args.last_name.clone(),
        timezone: Some(args.timezone.clone()),
        uuid: args.uuid.as_ref().map(|s| Some(serde_json::Value::String(s.clone()))),
        };
    // Build query parameters for create operation
    let limit_param = args.limit.map(|v| v as i32);
    let offset_param = args.offset.map(|v| v as i32);
    let resp = crate::apis::persons_api::persons_post(&config, req_body, limit_param, offset_param).await?;
    let json_output = serde_json::to_string_pretty(&resp)?;
    println!("{}", json_output);
    Ok(())
}

pub async fn handle_persons_get(
    ctx: &ApiContext,
    args: &ListArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build query parameters - openapi-generator functions take individual Option parameters
    let last_name_param = args.last_name.as_ref().map(|s| s.as_str());
    let limit_param = args.limit.map(|v| v as i32);
    let offset_param = args.offset.map(|v| v as i32);
    let resp = crate::apis::persons_api::persons_get(&config, last_name_param, limit_param, offset_param).await?;
    let json_output = serde_json::to_string_pretty(&resp)?;
    println!("{}", json_output);
    Ok(())
}

pub async fn handle_persons_uuid_delete(
    ctx: &ApiContext,
    args: &DeleteArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build query parameters for instance operations
    // DELETE operations may return empty responses (204 No Content)
    let resp_result = crate::apis::persons_api::persons_uuid_delete(&config, &args.uuid).await;
    match resp_result {
        Ok(data) => {
            let json_output = serde_json::to_string_pretty(&data)?;
            println!("{}", json_output);
        },
        Err(crate::apis::Error::Serde(e)) => {
            let error_msg = e.to_string();
            if error_msg.contains("content type") || error_msg.contains("application/octet-stream") || error_msg.contains("cannot be converted") {
                println!("{}", r#"{"status": "deleted"}"#);
            } else {
                return Err(Box::new(e));
            }
        },
        Err(e) => return Err(Box::new(e)),
    }
    Ok(())
}

pub async fn handle_persons_uuid_get(
    ctx: &ApiContext,
    args: &GetArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build query parameters for instance operations
    let last_name_param = args.last_name.as_ref().map(|s| s.as_str());
    let resp = crate::apis::persons_api::persons_uuid_get(&config, &args.uuid, last_name_param).await?;
    let json_output = serde_json::to_string_pretty(&resp)?;
    println!("{}", json_output);
    Ok(())
}

pub async fn handle_persons_uuid_put(
    ctx: &ApiContext,
    args: &UpdateArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build request body for update operation
    let req_body = crate::models::UpdatePerson {
        age: args.age.map(|v| v as i32),
        first_name: args.first_name.clone(),
        hobbies: args.hobbies.clone(),
        last_name: args.last_name.clone(),
        timezone: args.timezone.clone(),
        uuid: None,
        };

    let resp = crate::apis::persons_api::persons_uuid_put(&config, req_body, &args.uuid).await?;
    let json_output = serde_json::to_string_pretty(&resp)?;
    println!("{}", json_output);
    Ok(())
}

