// Auto-generated CLI module - generated by firestone
use clap::{Parser, Subcommand};
use serde_json;

/// Shared connection parameters passed to every handler.
/// Each handler builds its own typed client-crate Configuration from these.
/// `base_url` is `None` means "use the client crate's compiled-in default".
pub struct ApiContext {
    pub base_url: Option<String>,
    pub api_key: Option<String>,
}

#[derive(Subcommand, Debug)]
pub enum PostalCodesCommands {
    /// Create a new postal code in this collection, a new UUID key will be created
    Create(CreateArgs),
    /// List all postal codes in this collection
    List(ListArgs),
    /// Delete operation for postal_codes
    Delete(DeleteArgs),
    /// Get a specific postal code from this collection
    Get(GetArgs),
    }

#[derive(Parser, Debug)]
pub struct CreateArgs {
/// Limit the number of responses back
    #[arg(long)]
    pub limit: Option<i64>,
    /// The postal code's name/id
    #[arg(long)]
    pub name: Option<String>,
    /// The offset to start returning resources
    #[arg(long)]
    pub offset: Option<i64>,
    /// A UUID associated to this postal code
    #[arg(long)]
    pub uuid: Option<String>,
    }

#[derive(Parser, Debug)]
pub struct ListArgs {
/// Limit the number of responses back
    #[arg(long)]
    pub limit: Option<i64>,
    /// Filter by name
    #[arg(long)]
    pub name: Option<String>,
    /// The offset to start returning resources
    #[arg(long)]
    pub offset: Option<i64>,
    }

#[derive(Parser, Debug)]
pub struct DeleteArgs {
/// 
    pub uuid: String,
    }

#[derive(Parser, Debug)]
pub struct GetArgs {
/// Filter by name
    #[arg(long)]
    pub name: Option<String>,
    /// 
    pub uuid: String,
    }

pub async fn handle_postal_codes_command(
    ctx: &ApiContext,
    cmd: &PostalCodesCommands,
) -> Result<(), Box<dyn std::error::Error>> {
    match cmd {
PostalCodesCommands::Create(args) => {
            handle_postal_codes_post(ctx, args).await
        },
PostalCodesCommands::List(args) => {
            handle_postal_codes_get(ctx, args).await
        },
PostalCodesCommands::Delete(args) => {
            handle_postal_codes_uuid_delete(ctx, args).await
        },
PostalCodesCommands::Get(args) => {
            handle_postal_codes_uuid_get(ctx, args).await
        },
}
}

pub async fn handle_postal_codes_post(
    ctx: &ApiContext,
    args: &CreateArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build request body for create operation
    let req_body = crate::models::CreatePostalCode {
        name: args.name.clone(),
        uuid: args.uuid.as_ref().map(|s| Some(serde_json::Value::String(s.clone()))),
        };
    // Build query parameters for create operation
    let limit_param = args.limit.map(|v| v as i32);
    let offset_param = args.offset.map(|v| v as i32);
    let resp = crate::apis::postal_codes_api::postal_codes_post(&config, req_body, limit_param, offset_param).await?;
    let json_output = serde_json::to_string_pretty(&resp)?;
    println!("{}", json_output);
    Ok(())
}

pub async fn handle_postal_codes_get(
    ctx: &ApiContext,
    args: &ListArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build query parameters - openapi-generator functions take individual Option parameters
    let name_param = args.name.as_ref().map(|s| s.as_str());
    let limit_param = args.limit.map(|v| v as i32);
    let offset_param = args.offset.map(|v| v as i32);
    let resp = crate::apis::postal_codes_api::postal_codes_get(&config, name_param, limit_param, offset_param).await?;
    let json_output = serde_json::to_string_pretty(&resp)?;
    println!("{}", json_output);
    Ok(())
}

pub async fn handle_postal_codes_uuid_delete(
    ctx: &ApiContext,
    args: &DeleteArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build query parameters for instance operations
    // DELETE operations may return empty responses (204 No Content)
    let resp_result = crate::apis::postal_codes_api::postal_codes_uuid_delete(&config, &args.uuid).await;
    match resp_result {
        Ok(data) => {
            let json_output = serde_json::to_string_pretty(&data)?;
            println!("{}", json_output);
        },
        Err(crate::apis::Error::Serde(e)) => {
            let error_msg = e.to_string();
            if error_msg.contains("content type") || error_msg.contains("application/octet-stream") || error_msg.contains("cannot be converted") {
                println!("{}", r#"{"status": "deleted"}"#);
            } else {
                return Err(Box::new(e));
            }
        },
        Err(e) => return Err(Box::new(e)),
    }
    Ok(())
}

pub async fn handle_postal_codes_uuid_get(
    ctx: &ApiContext,
    args: &GetArgs,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = crate::apis::configuration::Configuration::default();
    if let Some(ref url) = ctx.base_url {
        config.base_path = url.clone();
    }
    if let Some(ref key) = ctx.api_key {
        config.api_key = Some(crate::apis::configuration::ApiKey {
            prefix: Some("Bearer".to_string()),
            key: key.clone(),
        });
    }
    // Build query parameters for instance operations
    let name_param = args.name.as_ref().map(|s| s.as_str());
    let resp = crate::apis::postal_codes_api::postal_codes_uuid_get(&config, &args.uuid, name_param).await?;
    let json_output = serde_json::to_string_pretty(&resp)?;
    println!("{}", json_output);
    Ok(())
}

