//! The validation engine.
//!
//! This file is generated by firestone but never changes: all of the
//! per-project detail lives in `rules.rs`.

use std::collections::HashMap;

use serde_json::Value;

use super::ports::Error;
use super::ports::RefRequest;
use super::ports::Resolved;
use super::ports::Resolver;
use super::ports::ValidationError;
use super::ports::Violation;
use super::rules::Ref;
use super::rules::Rule;

/// What is being validated, and everything the rules need to judge it.
///
/// Built with the chaining setters, so only what a rule actually reads has to be
/// supplied:
///
/// ```ignore
/// let request = Request::new("patch", "addressbook").body(&body).old(&current);
/// validate(request, &resolver).await?;
/// ```
#[derive(Clone, Debug)]
pub struct Request<'a> {
    /// The HTTP method being performed, lowercase.
    pub op: &'a str,
    /// The resource kind being operated on, as written in the schema.
    pub resource: &'a str,
    /// The request body.
    pub body: Option<&'a Value>,
    /// The resource as it currently stands, needed by PATCH, PUT and DELETE rules.
    pub old: Option<&'a Value>,
    /// Request scoped context: the caller's roles, the tenant, a trace id.
    pub ctx: Option<&'a Value>,
    /// The resource as it will be, when you would rather work that out yourself.
    pub subject: Option<&'a Value>,
}

impl<'a> Request<'a> {
    /// Start a request for the given method and resource kind.
    pub fn new(op: &'a str, resource: &'a str) -> Self {
        Request {
            op,
            resource,
            body: None,
            old: None,
            ctx: None,
            subject: None,
        }
    }

    /// Set the request body.
    pub fn body(mut self, body: &'a Value) -> Self {
        self.body = Some(body);
        self
    }

    /// Set the resource as it currently stands.
    pub fn old(mut self, old: &'a Value) -> Self {
        self.old = Some(old);
        self
    }

    /// Set the request context, read by the rules and handed to the resolver.
    pub fn ctx(mut self, ctx: &'a Value) -> Self {
        self.ctx = Some(ctx);
        self
    }

    /// Set the resulting resource explicitly, instead of merging `body` over `old`.
    ///
    /// Needed for anything whose update semantics are not a plain merge, and for
    /// endpoints that update one attribute rather than a whole resource.
    pub fn subject(mut self, subject: &'a Value) -> Self {
        self.subject = Some(subject);
        self
    }
}

/// Look up a dotted path such as `person.first_name`.
///
/// Returns `None` when any part of the path is absent, which is distinct from
/// finding a `null`.
pub fn resolve_path<'a>(data: &'a Value, path: &str) -> Option<&'a Value> {
    let mut current = data;
    for part in path.split('.') {
        current = current.get(part)?;
    }

    Some(current)
}

/// Apply a partial body over the current resource, nested objects included.
///
/// Nested objects are merged, so a body that touches one field of an embedded
/// object leaves the rest of that object alone. Everything else is replaced
/// outright: lists wholesale, and an explicit null as a null rather than as a
/// removal. That last point is where this differs from RFC 7386 JSON Merge Patch,
/// which deletes a member set to null.
///
/// If your API implements merge patch properly, or JSON Patch, or anything else,
/// do not rely on this: work out the resulting document yourself and hand it to
/// [`Request::subject`].
pub fn merge(old: &Value, body: &Value) -> Value {
    let (Some(old_object), Some(body_object)) = (old.as_object(), body.as_object()) else {
        return body.clone();
    };

    let mut merged = old_object.clone();
    for (key, value) in body_object {
        match merged.get(key) {
            Some(current) if current.is_object() && value.is_object() => {
                merged.insert(key.clone(), merge(current, value));
            }
            _ => {
                merged.insert(key.clone(), value.clone());
            }
        }
    }

    Value::Object(merged)
}

fn is_empty(value: &Value) -> bool {
    value.as_object().is_none_or(|object| object.is_empty())
}

/// Work out the object the rules are evaluated against.
///
/// `op` is the normalised method, so that which rules run and what they run
/// against can never disagree.
fn subject_of(request: &Request<'_>, op: &str) -> Value {
    if let Some(subject) = request.subject {
        return subject.clone();
    }

    let body = request
        .body
        .cloned()
        .unwrap_or_else(|| Value::Object(Default::default()));
    let old = request
        .old
        .cloned()
        .unwrap_or_else(|| Value::Object(Default::default()));

    if op == "delete" {
        return if is_empty(&old) { body } else { old };
    }
    if op == "patch" && !is_empty(&old) {
        return merge(&old, &body);
    }

    body
}

/// Interpolate `{self.city}` style placeholders in an error message.
fn format_message(message: &str, scope: &Value) -> String {
    let mut out = String::with_capacity(message.len());
    let mut rest = message;

    while let Some(start) = rest.find('{') {
        out.push_str(&rest[..start]);
        rest = &rest[start..];

        let Some(end) = rest.find('}') else {
            break;
        };
        let path = &rest[1..end];
        let is_path = !path.is_empty()
            && path.starts_with(|c: char| c.is_ascii_alphabetic() || c == '_')
            && path
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '.');

        match is_path.then(|| resolve_path(scope, path)).flatten() {
            Some(value) => out.push_str(&render(value)),
            None => out.push_str(&rest[..=end]),
        }
        rest = &rest[end + 1..];
    }
    out.push_str(rest);

    out
}

/// Render a value the way it should read inside a message, strings unquoted.
fn render(value: &Value) -> String {
    match value {
        Value::String(text) => text.clone(),
        other => other.to_string(),
    }
}

/// Whether an existence rule is checking a reference that did not change.
///
/// A reference that is the same as the one already stored was checked when it was
/// stored, so an update that leaves it alone does not need to look it up again.
fn unchanged(rule: &Rule, subject: &Value, old: &Value) -> bool {
    if rule.kind != "exists" || is_empty(old) {
        return false;
    }

    rule.refs.iter().all(|reference| {
        resolve_path(old, &reference.value) == resolve_path(subject, &reference.value)
    })
}

/// Get the first lookup this rule needed but did not get, if any.
///
/// A rule that reads through a lookup cannot be evaluated when that lookup found
/// nothing, so rather than let the expression blow up, the rule simply fails. A
/// rule that is *about* absence declares its lookup `optional` and guards the
/// expression with `has()`.
fn unresolved<'a>(rule: &'a Rule, refs: &serde_json::Map<String, Value>) -> Option<&'a Ref> {
    rule.refs
        .iter()
        .find(|reference| !reference.optional && !refs.contains_key(&reference.name))
}

/// Report a required lookup that found nothing, in terms of the lookup itself.
fn missing_violation(rule: &Rule, reference: &Ref, subject: &Value) -> Violation {
    let value = resolve_path(subject, &reference.value)
        .map(render)
        .unwrap_or_else(|| "None".to_string());

    Violation {
        rule: rule.name.clone(),
        resource: rule.resource.clone(),
        field: rule.field.clone().or_else(|| Some(reference.value.clone())),
        message: format!(
            "No {} found with {} '{}'.",
            reference.kind, reference.key, value
        ),
        status: rule.error.status,
    }
}

/// Work out every lookup the given rules need.
///
/// A rule whose lookup value is not present in the subject is skipped rather than
/// failed, so a PATCH that does not touch a referenced field is left alone.
type Plan<'a> = Vec<(&'a Rule, HashMap<String, String>)>;

fn plan<'a>(rules: &[&'a Rule], subject: &Value, old: &Value) -> (Plan<'a>, Vec<RefRequest>) {
    let mut requests: Vec<RefRequest> = Vec::new();
    let mut seen: Vec<String> = Vec::new();
    let mut runnable: Plan<'a> = Vec::new();

    for rule in rules {
        if unchanged(rule, subject, old) {
            continue;
        }

        let mut lookups = HashMap::new();
        let mut skip = false;
        for reference in &rule.refs {
            let Some(value) = resolve_path(subject, &reference.value) else {
                skip = true;
                break;
            };
            if value.is_null() {
                skip = true;
                break;
            }

            let request = RefRequest {
                kind: reference.kind.clone(),
                key: reference.key.clone(),
                value: value.clone(),
            };
            let id = request.id();
            if !seen.contains(&id) {
                seen.push(id.clone());
                requests.push(request);
            }
            lookups.insert(reference.name.clone(), id);
        }

        if !skip {
            runnable.push((rule, lookups));
        }
    }

    (runnable, requests)
}

#[cfg(feature = "cel")]
mod cel {
    use std::collections::HashMap;
    use std::sync::Arc;
    use std::sync::LazyLock;
    use std::sync::RwLock;

    use cel_interpreter::Context;
    use cel_interpreter::Program;
    use cel_interpreter::Value as CelValue;
    use serde_json::Value;

    use super::Error;
    use super::Rule;

    static PROGRAMS: LazyLock<RwLock<HashMap<String, Arc<Program>>>> =
        LazyLock::new(|| RwLock::new(HashMap::new()));

    fn compiled(expr: &str, rule: &str) -> Result<Arc<Program>, Error> {
        if let Some(program) = PROGRAMS
            .read()
            .ok()
            .and_then(|cache| cache.get(expr).cloned())
        {
            return Ok(program);
        }

        let program = Program::compile(expr).map_err(|err| {
            Error::Rule(format!(
                "Rule '{rule}' has an invalid CEL expression: {err}"
            ))
        })?;
        let program = Arc::new(program);
        if let Ok(mut cache) = PROGRAMS.write() {
            cache.insert(expr.to_string(), Arc::clone(&program));
        }

        Ok(program)
    }

    /// Evaluate a rule's CEL expression against the given scope.
    pub fn evaluate(rule: &Rule, scope: &Value) -> Result<bool, Error> {
        let expr = rule
            .expr
            .as_deref()
            .ok_or_else(|| Error::Rule(format!("Rule '{}' has no expression", rule.name)))?;
        let program = compiled(expr, &rule.name)?;

        let mut context = Context::default();
        for (name, value) in scope.as_object().into_iter().flatten() {
            context
                .add_variable(name.as_str(), value.clone())
                .map_err(|err| {
                    Error::Rule(format!(
                        "Rule '{}' could not be given {name}: {err}",
                        rule.name
                    ))
                })?;
        }

        match program.execute(&context) {
            Ok(CelValue::Bool(passed)) => Ok(passed),
            Ok(other) => Err(Error::Rule(format!(
                "Rule '{}' evaluated to {other:?} rather than a boolean",
                rule.name
            ))),
            Err(err) => Err(Error::Rule(format!(
                "Rule '{}' could not be evaluated: {err}",
                rule.name
            ))),
        }
    }
}

#[cfg(not(feature = "cel"))]
mod cel {
    use serde_json::Value;

    use super::Error;
    use super::Rule;

    /// Without the `cel` feature there is no way to evaluate an expression.
    pub fn evaluate(rule: &Rule, _scope: &Value) -> Result<bool, Error> {
        Err(Error::Rule(format!(
            "Rule '{}' carries a CEL expression, so this crate needs the 'cel' feature",
            rule.name
        )))
    }
}

/// Evaluate a single rule that has had all of its lookups resolved.
fn passes(rule: &Rule, scope: &Value) -> Result<bool, Error> {
    match rule.kind.as_str() {
        // Its lookup is required, so reaching here means the resource was found.
        "exists" => Ok(true),
        "immutable" => {
            let old = &scope["old"];
            if is_empty(old) {
                return Ok(true);
            }
            let field = rule.field.as_deref().unwrap_or_default();

            Ok(resolve_path(old, field) == resolve_path(&scope["self"], field))
        }
        "expr" => cel::evaluate(rule, scope),
        other => Err(Error::Rule(format!(
            "Rule '{}' has an unknown kind '{other}'",
            rule.name
        ))),
    }
}

/// Run every rule in `rules` that applies to this request.
///
/// Prefer the `validate` in the parent module, which uses the generated rules.
pub async fn validate_with_rules(
    rules: &HashMap<String, Vec<Rule>>,
    request: Request<'_>,
    resolver: Option<&mut dyn Resolver>,
) -> Result<(), Error> {
    let op = request.op.to_lowercase();
    let Some(all) = rules.get(request.resource) else {
        return Ok(());
    };

    let applicable: Vec<&Rule> = all
        .iter()
        .filter(|rule| rule.methods.iter().any(|m| m == &op))
        .collect();
    if applicable.is_empty() {
        return Ok(());
    }

    let empty = Value::Object(Default::default());
    let ctx = request.ctx.cloned().unwrap_or_else(|| empty.clone());
    let old = request.old.cloned().unwrap_or_else(|| empty.clone());
    let subject = subject_of(&request, &op);

    let (runnable, requests) = plan(&applicable, &subject, &old);

    let mut resolved: Resolved = HashMap::new();
    if !requests.is_empty() {
        // Rules reading only self, old and ctx need nothing fetched, so a resolver is
        // only required once a lookup has actually been planned.
        let Some(resolver) = resolver else {
            return Err(Error::Rule(format!(
                "Validating {op} on {} needs {} lookup(s) but no resolver was given",
                request.resource,
                requests.len()
            )));
        };
        resolved = resolver
            .resolve(&requests, &ctx)
            .await
            .map_err(Error::Resolver)?;
    }

    let mut violations = Vec::new();
    for (rule, lookups) in runnable {
        let mut refs = serde_json::Map::new();
        for (name, id) in &lookups {
            match resolved.get(id) {
                Some(found) if !found.is_null() => {
                    refs.insert(name.clone(), found.clone());
                }
                _ => {}
            }
        }

        if let Some(reference) = unresolved(rule, &refs) {
            violations.push(missing_violation(rule, reference, &subject));
            continue;
        }

        let scope = serde_json::json!({
            "self": subject,
            "old": old,
            "ctx": ctx,
            "refs": Value::Object(refs),
        });

        if passes(rule, &scope)? {
            continue;
        }

        violations.push(Violation {
            rule: rule.name.clone(),
            resource: rule.resource.clone(),
            field: rule.field.clone(),
            message: format_message(&rule.error.message, &scope),
            status: rule.error.status,
        });
    }

    if violations.is_empty() {
        return Ok(());
    }

    Err(Error::Validation(ValidationError { violations }))
}
