# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from addressbook.models.person import Person


class Addressbook(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Addressbook - a model defined in OpenAPI

        addrtype: The addrtype of this Addressbook.
        city: The city of this Addressbook.
        country: The country of this Addressbook.
        person: The person of this Addressbook [Optional].
        state: The state of this Addressbook.
        street: The street of this Addressbook.
    """

    addrtype: str = Field(alias="addrtype")
    city: str = Field(alias="city")
    country: str = Field(alias="country")
    person: Optional[Person] = Field(alias="person", default=None)
    state: str = Field(alias="state")
    street: str = Field(alias="street")


Addressbook.update_forward_refs()
