# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class AddressbookAddressKeyPutRequestInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AddressbookAddressKeyPutRequestInner - a model defined in OpenAPI

        addrtype: The addrtype of this AddressbookAddressKeyPutRequestInner.
        city: The city of this AddressbookAddressKeyPutRequestInner.
        country: The country of this AddressbookAddressKeyPutRequestInner.
        people: The people of this AddressbookAddressKeyPutRequestInner [Optional].
        person: The person of this AddressbookAddressKeyPutRequestInner [Optional].
        state: The state of this AddressbookAddressKeyPutRequestInner.
        street: The street of this AddressbookAddressKeyPutRequestInner.
    """

    addrtype: str = Field(alias="addrtype")
    city: str = Field(alias="city")
    country: str = Field(alias="country")
    people: Optional[List[str]] = Field(alias="people", default=None)
    person: Optional[object] = Field(alias="person", default=None)
    state: str = Field(alias="state")
    street: str = Field(alias="street")


AddressbookAddressKeyPutRequestInner.update_forward_refs()
