//! The interfaces of the validation package.
//!
//! This file is generated by firestone but never changes: it is the contract
//! between the generated rules and your application. The only thing you have to
//! write is a [`Resolver`].

use std::collections::HashMap;
use std::error::Error as StdError;
use std::fmt;

use async_trait::async_trait;
use serde_json::json;
use serde_json::Value;

/// What a resolver hands back: the resource found, keyed by [`RefRequest::id`].
pub type Resolved = HashMap<String, Value>;

/// Whatever went wrong while talking to your storage.
pub type ResolverError = Box<dyn StdError + Send + Sync>;

/// A single lookup a rule needs before it can be evaluated.
#[derive(Clone, Debug, PartialEq)]
pub struct RefRequest {
    /// The resource kind to look up, e.g. `persons`.
    pub kind: String,
    /// The path into that resource to match on, e.g. `first_name`.
    pub key: String,
    /// The value to match, taken from the request body.
    pub value: Value,
}

impl RefRequest {
    /// A stable identifier for this lookup, used to key the resolved results.
    pub fn id(&self) -> String {
        format!("{}/{}/{}", self.kind, self.key, self.value)
    }
}

/// Fetches the resources that validation rules depend on.
///
/// Implement this against whatever you already have: a database, an ORM, a
/// cache, another service. Firestone works out *what* needs fetching; this is
/// the only place that knows *how*.
///
/// `resolve` is handed every lookup needed by a single request at once, already
/// de-duplicated, so a request that touches ten rules still costs one round trip.
///
/// `ctx` is the request context passed to `validate`, for whatever scoping a
/// lookup needs: the tenant, the caller's authorisation scope, a trace id. Rules
/// can read it too, so it is plain JSON; a database handle or transaction belongs
/// on the implementing struct rather than in there.
///
/// `resolve` takes `&mut self` deliberately. Validation has to read through the
/// same transaction as the mutation it guards, or the check races the write, and a
/// transaction is normally held mutably. Building the resolver per request and
/// handing it to `validate` mutably is therefore the straightforward path; an
/// implementation that needs no mutation simply ignores it.
#[async_trait]
pub trait Resolver: Send {
    /// Resolve the given lookups.
    ///
    /// Leave an entry out, or map it to `Value::Null`, for anything that does not
    /// exist.
    async fn resolve(
        &mut self,
        requests: &[RefRequest],
        ctx: &Value,
    ) -> Result<Resolved, ResolverError>;
}

/// A single rule that failed.
#[derive(Clone, Debug, PartialEq)]
pub struct Violation {
    /// The name of the rule.
    pub rule: String,
    /// The resource kind that was validated.
    pub resource: String,
    /// The field the rule applies to, if any.
    pub field: Option<String>,
    /// Why the rule failed.
    pub message: String,
    /// The status this violation asks for.
    pub status: u16,
}

impl Violation {
    /// This violation in the shape used by the problem document.
    pub fn to_json(&self) -> Value {
        let mut violation = json!({
            "rule": self.rule,
            "resource": self.resource,
            "message": self.message,
        });
        if let Some(field) = &self.field {
            violation["field"] = json!(field);
        }

        violation
    }
}

/// One or more validation rules rejected the request.
#[derive(Clone, Debug)]
pub struct ValidationError {
    /// Every rule that failed for this request, not just the first.
    pub violations: Vec<Violation>,
}

impl ValidationError {
    /// The status to respond with, the highest of any violation's.
    pub fn status(&self) -> u16 {
        self.violations
            .iter()
            .map(|violation| violation.status)
            .max()
            .unwrap_or(422)
    }

    /// An RFC 9457 problem detail describing every violation.
    ///
    /// Serve it as `application/problem+json`, which is what the generated
    /// OpenAPI document declares.
    pub fn to_problem(&self) -> Value {
        json!({
            "type": "about:blank",
            "title": "Validation failed",
            "status": self.status(),
            "detail": self.violations.first().map(|v| v.message.clone()).unwrap_or_default(),
            "violations": self.violations.iter().map(Violation::to_json).collect::<Vec<_>>(),
        })
    }
}

impl fmt::Display for ValidationError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let messages: Vec<&str> = self
            .violations
            .iter()
            .map(|violation| violation.message.as_str())
            .collect();
        write!(f, "{}", messages.join("; "))
    }
}

impl StdError for ValidationError {}

/// Everything `validate` can go wrong with.
///
/// The split matters: [`Error::Validation`] is a request to refuse, and the other
/// two are failures on your side that should not be reported as a rejected body.
#[derive(Debug)]
pub enum Error {
    /// Rules rejected the request. Answer with [`ValidationError::to_problem`].
    Validation(ValidationError),
    /// A rule could not be evaluated at all, which is a bug in the rule. Answer 500.
    Rule(String),
    /// The resolver could not answer. Answer 500, or 503 if it was transient.
    Resolver(ResolverError),
}

impl Error {
    /// The status this failure asks for.
    pub fn status(&self) -> u16 {
        match self {
            Error::Validation(error) => error.status(),
            Error::Rule(_) | Error::Resolver(_) => 500,
        }
    }
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Error::Validation(error) => write!(f, "{error}"),
            Error::Rule(message) => write!(f, "rule could not be evaluated: {message}"),
            Error::Resolver(error) => write!(f, "resolver failed: {error}"),
        }
    }
}

impl StdError for Error {
    fn source(&self) -> Option<&(dyn StdError + 'static)> {
        match self {
            Error::Validation(error) => Some(error),
            Error::Resolver(error) => Some(error.as_ref()),
            Error::Rule(_) => None,
        }
    }
}

impl From<ValidationError> for Error {
    fn from(error: ValidationError) -> Self {
        Error::Validation(error)
    }
}
