# coding: utf-8

# flake8: noqa
"""
    Example person and addressbook API

    Example person and addressbook API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from addressbook.client.models.addressbook import Addressbook
from addressbook.client.models.addressbook_address_key_person_uuid_put_request_inner import (
    AddressbookAddressKeyPersonUuidPutRequestInner,
)
from addressbook.client.models.addressbook_address_key_put_request_inner import (
    AddressbookAddressKeyPutRequestInner,
)
from addressbook.client.models.person import Person
from addressbook.client.models.persons import Persons
