# coding: utf-8

# flake8: noqa
"""
    Example person and addressbook API

    Example person and addressbook API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


# import models into model package
from addressbook.client.models.addressbook import Addressbook
from addressbook.client.models.create_addressbook import CreateAddressbook
from addressbook.client.models.create_person import CreatePerson
from addressbook.client.models.person import Person
from addressbook.client.models.update_addressbook import UpdateAddressbook
from addressbook.client.models.update_person import UpdatePerson
