# coding: utf-8

"""
    Example person and addressbook API

    Example person and addressbook API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, validator
from addressbook.client.models.person import Person


class Addressbook(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    addrtype: StrictStr = Field(..., description="The address type, e.g. work or home")
    city: StrictStr = Field(..., description="The city of this address")
    country: StrictStr = Field(..., description="The country of this address")
    person: Optional[Person] = None
    state: StrictStr = Field(..., description="The state of this address")
    street: StrictStr = Field(..., description="The street and civic number of this address")
    __properties = ["addrtype", "city", "country", "person", "state", "street"]

    @validator("addrtype")
    def addrtype_validate_enum(cls, v):
        if v not in ("work", "home"):
            raise ValueError("must validate the enum values ('work', 'home')")
        return v

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Addressbook:
        """Create an instance of Addressbook from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of person
        if self.person:
            _dict["person"] = self.person.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Addressbook:
        """Create an instance of Addressbook from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return Addressbook.parse_obj(obj)

        _obj = Addressbook.parse_obj(
            {
                "addrtype": obj.get("addrtype"),
                "city": obj.get("city"),
                "country": obj.get("country"),
                "person": Person.from_dict(obj.get("person"))
                if obj.get("person") is not None
                else None,
                "state": obj.get("state"),
                "street": obj.get("street"),
            }
        )
        return _obj
