//! How this API says no.
//!
//! Every failure leaves as an RFC 9457 problem document served as
//! `application/problem+json`, which is what the generated OpenAPI document
//! declares. Generated by firestone; it does not change between projects.

use axum::http::header;
use axum::http::HeaderMap;
use axum::http::HeaderValue;
use axum::http::StatusCode;
use axum::response::IntoResponse;
use axum::response::Response;
use serde_json::json;
use serde_json::Value;

/// Anything a handler can refuse or fail with.
#[derive(Debug)]
pub enum ApiError {
    /// No such resource.
    NotFound { resource: String, key: String },
    /// The body did not survive the rules declared in the schema.
    Validation(Value),
    /// No, or unusable, credentials.
    Unauthorized(String),
    /// Too many requests from this caller.
    RateLimited { retry_after: u64 },
    /// A route firestone generated but the backend does not implement yet.
    NotImplemented(String),
    /// Anything else, which is this service's fault.
    Internal(String),
}

impl ApiError {
    /// The status this failure asks for.
    pub fn status(&self) -> StatusCode {
        match self {
            ApiError::NotFound { .. } => StatusCode::NOT_FOUND,
            ApiError::Validation(problem) => problem
                .get("status")
                .and_then(Value::as_u64)
                .and_then(|status| StatusCode::from_u16(status as u16).ok())
                .unwrap_or(StatusCode::UNPROCESSABLE_ENTITY),
            ApiError::Unauthorized(_) => StatusCode::UNAUTHORIZED,
            ApiError::RateLimited { .. } => StatusCode::TOO_MANY_REQUESTS,
            ApiError::NotImplemented(_) => StatusCode::NOT_IMPLEMENTED,
            ApiError::Internal(_) => StatusCode::INTERNAL_SERVER_ERROR,
        }
    }

    /// This failure as an RFC 9457 problem document.
    pub fn to_problem(&self) -> Value {
        // A validation failure already is one, so it is passed through whole and
        // keeps its per-rule violations.
        if let ApiError::Validation(problem) = self {
            return problem.clone();
        }

        let (title, detail) = match self {
            ApiError::NotFound { resource, key } => {
                ("Not found", format!("No {resource} with key '{key}'."))
            }
            ApiError::Unauthorized(detail) => ("Unauthorized", detail.clone()),
            ApiError::RateLimited { retry_after } => {
                ("Too many requests", format!("Try again in {retry_after}s."))
            }
            ApiError::NotImplemented(detail) => ("Not implemented", detail.clone()),
            ApiError::Internal(detail) => ("Internal server error", detail.clone()),
            ApiError::Validation(_) => unreachable!("handled above"),
        };

        json!({
            "type": "about:blank",
            "title": title,
            "status": self.status().as_u16(),
            "detail": detail,
        })
    }
}

impl std::fmt::Display for ApiError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.to_problem())
    }
}

impl std::error::Error for ApiError {}

impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        let status = self.status();
        let body = self.to_problem();

        let mut headers = HeaderMap::new();
        headers.insert(
            header::CONTENT_TYPE,
            HeaderValue::from_static("application/problem+json"),
        );
        match &self {
            ApiError::RateLimited { retry_after } => {
                if let Ok(value) = HeaderValue::from_str(&retry_after.to_string()) {
                    headers.insert(header::RETRY_AFTER, value);
                }
            }
            ApiError::Unauthorized(_) => {
                headers.insert(header::WWW_AUTHENTICATE, HeaderValue::from_static("Bearer"));
            }
            _ => {}
        }

        (status, headers, axum::Json(body)).into_response()
    }
}
