//! The handlers, from the paths and methods in the resource schemas.
//!
//! Generated by firestone. Do not edit: change the resource files and regenerate.
//!
//! Each handler does the same three things — pull the request apart, enforce the
//! rules the schema declares, then hand off to the [`Backend`](crate::backend::Backend).
//! Only the last of those is yours to write.

/// Handlers for addressbook.
pub mod addressbook {
    use axum::extract::Path;
    use axum::extract::Query;
    use axum::extract::State;
    use axum::http::header;
    use axum::http::HeaderMap;
    use axum::http::HeaderValue;
    use axum::http::StatusCode;
    use axum::Json;
    use serde_json::Value;

    use crate::error::ApiError;
    use crate::models::Addressbook;
    use crate::models::AddressbookQuery;
    use crate::resolver::validate_request;
    use crate::resolver::validate_subject;
    use crate::AppState;

    /// The resource kind these handlers serve, as written in the schema.
    const RESOURCE: &str = "addressbook";

    /// Where this resource is mounted, for the Location header on a create.
    const PATH: &str = "/addressbook";

    /// The attributes with endpoints of their own, so an unknown one is a 404
    /// rather than something the caller can invent.
    const ATTRS: &[&str] = &[
        "person", "addrtype", "street", "city", "state", "country", "people", "is_valid",
    ];

    /// Refuse an attribute the schema does not expose.
    fn known(attr: &str) -> Result<(), ApiError> {
        if ATTRS.contains(&attr) {
            return Ok(());
        }

        Err(ApiError::NotFound {
            resource: format!("{RESOURCE} attribute"),
            key: attr.to_string(),
        })
    }

    /// Load the resource an attribute belongs to.
    async fn owner(state: &AppState, key: &str) -> Result<Value, ApiError> {
        state
            .backend
            .get(RESOURCE, key)
            .await?
            .ok_or(ApiError::NotFound {
                resource: RESOURCE.to_string(),
                key: key.to_string(),
            })
    }

    /// List every addressbook.
    pub async fn get_collection(
        State(state): State<AppState>,
        Query(query): Query<AddressbookQuery>,
    ) -> Result<Json<Vec<Value>>, ApiError> {
        // The query parameters the schema declares are parsed for you; filtering on
        // them is a storage concern, so it belongs in your Backend.
        let _ = query;

        Ok(Json(state.backend.list(RESOURCE).await?))
    }

    /// Create a addressbook, giving it a new key.
    pub async fn post_collection(
        State(state): State<AppState>,
        Json(body): Json<Addressbook>,
    ) -> Result<(StatusCode, HeaderMap, Json<Value>), ApiError> {
        let body =
            serde_json::to_value(&body).map_err(|err| ApiError::Internal(err.to_string()))?;
        validate_request(&state, "post", RESOURCE, Some(&body), None).await?;

        let (key, created) = state.backend.create(RESOURCE, body).await?;
        tracing::info!(resource = RESOURCE, key, "created");

        // The key is minted by the backend, so the caller is told where it went.
        let mut headers = HeaderMap::new();
        if let Ok(location) = HeaderValue::from_str(&format!("{PATH}/{key}")) {
            headers.insert(header::LOCATION, location);
        }

        Ok((StatusCode::CREATED, headers, Json(created)))
    }

    /// Get one addressbook by its address_key.
    pub async fn get_instance(
        State(state): State<AppState>,
        Path(address_key): Path<String>,
    ) -> Result<Json<Value>, ApiError> {
        state
            .backend
            .get(RESOURCE, &address_key)
            .await?
            .map(Json)
            .ok_or(ApiError::NotFound {
                resource: RESOURCE.to_string(),
                key: address_key,
            })
    }

    /// Replace one addressbook.
    pub async fn put_instance(
        State(state): State<AppState>,
        Path(address_key): Path<String>,
        Json(body): Json<Addressbook>,
    ) -> Result<Json<Value>, ApiError> {
        let body =
            serde_json::to_value(&body).map_err(|err| ApiError::Internal(err.to_string()))?;
        // Rules that compare against the current state need it, so it is loaded
        // whether or not the backend would have needed it.
        let current = state.backend.get(RESOURCE, &address_key).await?;
        validate_request(&state, "put", RESOURCE, Some(&body), current.as_ref()).await?;

        Ok(Json(
            state.backend.replace(RESOURCE, &address_key, body).await?,
        ))
    }

    /// Delete one addressbook.
    pub async fn delete_instance(
        State(state): State<AppState>,
        Path(address_key): Path<String>,
    ) -> Result<StatusCode, ApiError> {
        // A delete has no body, so the rules are evaluated against the resource
        // that is about to go.
        let current = state.backend.get(RESOURCE, &address_key).await?;
        validate_request(&state, "delete", RESOURCE, None, current.as_ref()).await?;
        state.backend.delete(RESOURCE, &address_key).await?;
        tracing::info!(resource = RESOURCE, key = %address_key, "deleted");

        Ok(StatusCode::NO_CONTENT)
    }

    /// Get one attribute of a addressbook.
    ///
    /// axum answers HEAD here too, so the schema's `head` needs no route of its own.
    pub async fn get_attr(
        State(state): State<AppState>,
        Path((address_key, attr)): Path<(String, String)>,
    ) -> Result<Json<Value>, ApiError> {
        known(&attr)?;
        let resource = owner(&state, &address_key).await?;

        resource
            .get(&attr)
            .cloned()
            .map(Json)
            .ok_or(ApiError::NotFound {
                resource: format!("{RESOURCE} attribute"),
                key: attr,
            })
    }

    /// Replace one attribute of a addressbook.
    pub async fn put_attr(
        State(state): State<AppState>,
        Path((address_key, attr)): Path<(String, String)>,
        Json(value): Json<Value>,
    ) -> Result<Json<Value>, ApiError> {
        known(&attr)?;
        let current = owner(&state, &address_key).await?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| ApiError::Internal("the stored resource is not an object".into()))?
            .insert(attr, value);
        // The rules are written against the whole resource, so they are given the
        // resource as it will be rather than the attribute on its own.
        validate_subject(&state, "put", RESOURCE, &updated, Some(&current)).await?;

        state
            .backend
            .replace(RESOURCE, &address_key, updated)
            .await?;
        Ok(Json(Value::Null))
    }

    /// Remove one attribute of a addressbook.
    pub async fn delete_attr(
        State(state): State<AppState>,
        Path((address_key, attr)): Path<(String, String)>,
    ) -> Result<StatusCode, ApiError> {
        known(&attr)?;
        let current = owner(&state, &address_key).await?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| ApiError::Internal("the stored resource is not an object".into()))?
            .remove(&attr);
        validate_subject(&state, "put", RESOURCE, &updated, Some(&current)).await?;

        state
            .backend
            .replace(RESOURCE, &address_key, updated)
            .await?;
        Ok(StatusCode::NO_CONTENT)
    }
}

/// Handlers for persons.
pub mod persons {
    use axum::extract::Path;
    use axum::extract::Query;
    use axum::extract::State;
    use axum::http::header;
    use axum::http::HeaderMap;
    use axum::http::HeaderValue;
    use axum::http::StatusCode;
    use axum::Json;
    use serde_json::Value;

    use crate::error::ApiError;
    use crate::models::Person;
    use crate::models::PersonQuery;
    use crate::resolver::validate_request;
    use crate::AppState;

    /// The resource kind these handlers serve, as written in the schema.
    const RESOURCE: &str = "persons";

    /// Where this resource is mounted, for the Location header on a create.
    const PATH: &str = "/persons";

    /// List every persons.
    pub async fn get_collection(
        State(state): State<AppState>,
        Query(query): Query<PersonQuery>,
    ) -> Result<Json<Vec<Value>>, ApiError> {
        // The query parameters the schema declares are parsed for you; filtering on
        // them is a storage concern, so it belongs in your Backend.
        let _ = query;

        Ok(Json(state.backend.list(RESOURCE).await?))
    }

    /// Create a persons, giving it a new key.
    pub async fn post_collection(
        State(state): State<AppState>,
        Json(body): Json<Person>,
    ) -> Result<(StatusCode, HeaderMap, Json<Value>), ApiError> {
        let body =
            serde_json::to_value(&body).map_err(|err| ApiError::Internal(err.to_string()))?;
        validate_request(&state, "post", RESOURCE, Some(&body), None).await?;

        let (key, created) = state.backend.create(RESOURCE, body).await?;
        tracing::info!(resource = RESOURCE, key, "created");

        // The key is minted by the backend, so the caller is told where it went.
        let mut headers = HeaderMap::new();
        if let Ok(location) = HeaderValue::from_str(&format!("{PATH}/{key}")) {
            headers.insert(header::LOCATION, location);
        }

        Ok((StatusCode::CREATED, headers, Json(created)))
    }

    /// Get one persons by its uuid.
    pub async fn get_instance(
        State(state): State<AppState>,
        Path(uuid): Path<String>,
    ) -> Result<Json<Value>, ApiError> {
        state
            .backend
            .get(RESOURCE, &uuid)
            .await?
            .map(Json)
            .ok_or(ApiError::NotFound {
                resource: RESOURCE.to_string(),
                key: uuid,
            })
    }

    /// Replace one persons.
    pub async fn put_instance(
        State(state): State<AppState>,
        Path(uuid): Path<String>,
        Json(body): Json<Person>,
    ) -> Result<Json<Value>, ApiError> {
        let body =
            serde_json::to_value(&body).map_err(|err| ApiError::Internal(err.to_string()))?;
        // Rules that compare against the current state need it, so it is loaded
        // whether or not the backend would have needed it.
        let current = state.backend.get(RESOURCE, &uuid).await?;
        validate_request(&state, "put", RESOURCE, Some(&body), current.as_ref()).await?;

        Ok(Json(state.backend.replace(RESOURCE, &uuid, body).await?))
    }

    /// Delete one persons.
    pub async fn delete_instance(
        State(state): State<AppState>,
        Path(uuid): Path<String>,
    ) -> Result<StatusCode, ApiError> {
        // A delete has no body, so the rules are evaluated against the resource
        // that is about to go.
        let current = state.backend.get(RESOURCE, &uuid).await?;
        validate_request(&state, "delete", RESOURCE, None, current.as_ref()).await?;
        state.backend.delete(RESOURCE, &uuid).await?;
        tracing::info!(resource = RESOURCE, key = %uuid, "deleted");

        Ok(StatusCode::NO_CONTENT)
    }
}

/// Handlers for postal_codes.
pub mod postal_codes {
    use axum::extract::Path;
    use axum::extract::Query;
    use axum::extract::State;
    use axum::http::header;
    use axum::http::HeaderMap;
    use axum::http::HeaderValue;
    use axum::http::StatusCode;
    use axum::Json;
    use serde_json::Value;

    use crate::error::ApiError;
    use crate::models::PostalCode;
    use crate::models::PostalCodeQuery;
    use crate::AppState;

    /// The resource kind these handlers serve, as written in the schema.
    const RESOURCE: &str = "postal_codes";

    /// Where this resource is mounted, for the Location header on a create.
    const PATH: &str = "/postal_codes";

    /// The attributes with endpoints of their own, so an unknown one is a 404
    /// rather than something the caller can invent.
    const ATTRS: &[&str] = &["name"];

    /// Refuse an attribute the schema does not expose.
    fn known(attr: &str) -> Result<(), ApiError> {
        if ATTRS.contains(&attr) {
            return Ok(());
        }

        Err(ApiError::NotFound {
            resource: format!("{RESOURCE} attribute"),
            key: attr.to_string(),
        })
    }

    /// Load the resource an attribute belongs to.
    async fn owner(state: &AppState, key: &str) -> Result<Value, ApiError> {
        state
            .backend
            .get(RESOURCE, key)
            .await?
            .ok_or(ApiError::NotFound {
                resource: RESOURCE.to_string(),
                key: key.to_string(),
            })
    }

    /// List every postal_codes.
    pub async fn get_collection(
        State(state): State<AppState>,
        Query(query): Query<PostalCodeQuery>,
    ) -> Result<Json<Vec<Value>>, ApiError> {
        // The query parameters the schema declares are parsed for you; filtering on
        // them is a storage concern, so it belongs in your Backend.
        let _ = query;

        Ok(Json(state.backend.list(RESOURCE).await?))
    }

    /// Create a postal_codes, giving it a new key.
    pub async fn post_collection(
        State(state): State<AppState>,
        Json(body): Json<PostalCode>,
    ) -> Result<(StatusCode, HeaderMap, Json<Value>), ApiError> {
        let body =
            serde_json::to_value(&body).map_err(|err| ApiError::Internal(err.to_string()))?;

        let (key, created) = state.backend.create(RESOURCE, body).await?;
        tracing::info!(resource = RESOURCE, key, "created");

        // The key is minted by the backend, so the caller is told where it went.
        let mut headers = HeaderMap::new();
        if let Ok(location) = HeaderValue::from_str(&format!("{PATH}/{key}")) {
            headers.insert(header::LOCATION, location);
        }

        Ok((StatusCode::CREATED, headers, Json(created)))
    }

    /// Get one postal_codes by its uuid.
    pub async fn get_instance(
        State(state): State<AppState>,
        Path(uuid): Path<String>,
    ) -> Result<Json<Value>, ApiError> {
        state
            .backend
            .get(RESOURCE, &uuid)
            .await?
            .map(Json)
            .ok_or(ApiError::NotFound {
                resource: RESOURCE.to_string(),
                key: uuid,
            })
    }

    /// Delete one postal_codes.
    pub async fn delete_instance(
        State(state): State<AppState>,
        Path(uuid): Path<String>,
    ) -> Result<StatusCode, ApiError> {
        state.backend.delete(RESOURCE, &uuid).await?;
        tracing::info!(resource = RESOURCE, key = %uuid, "deleted");

        Ok(StatusCode::NO_CONTENT)
    }

    /// Get one attribute of a postal_codes.
    ///
    /// axum answers HEAD here too, so the schema's `head` needs no route of its own.
    pub async fn get_attr(
        State(state): State<AppState>,
        Path((uuid, attr)): Path<(String, String)>,
    ) -> Result<Json<Value>, ApiError> {
        known(&attr)?;
        let resource = owner(&state, &uuid).await?;

        resource
            .get(&attr)
            .cloned()
            .map(Json)
            .ok_or(ApiError::NotFound {
                resource: format!("{RESOURCE} attribute"),
                key: attr,
            })
    }

    /// Remove one attribute of a postal_codes.
    pub async fn delete_attr(
        State(state): State<AppState>,
        Path((uuid, attr)): Path<(String, String)>,
    ) -> Result<StatusCode, ApiError> {
        known(&attr)?;
        let current = owner(&state, &uuid).await?;

        let mut updated = current.clone();
        updated
            .as_object_mut()
            .ok_or_else(|| ApiError::Internal("the stored resource is not an object".into()))?
            .remove(&attr);

        state.backend.replace(RESOURCE, &uuid, updated).await?;
        Ok(StatusCode::NO_CONTENT)
    }
}
