//! Example person and addressbook API
//!
//! Example person and addressbook API
//!
//! Generated by firestone from the resource schemas. The router, models, handlers
//! and middleware are regenerated whenever the schemas change; the one thing you
//! write is a [`backend::Backend`].

pub mod backend;
pub mod error;
pub mod handlers;
pub mod middleware;
pub mod models;
pub mod resolver;
pub mod routes;
pub mod validation;

use std::sync::Arc;

pub use error::ApiError;
pub use routes::router;

/// Everything a handler is given besides the request itself.
#[derive(Clone)]
pub struct AppState {
    /// Where the data lives.
    pub backend: Arc<dyn backend::Backend>,
    /// Which bearer tokens are accepted on the secured routes.
    pub auth: Arc<middleware::Auth>,
    /// How often one caller may ask.
    pub rate_limit: Arc<middleware::RateLimit>,
}

impl AppState {
    /// Assemble the state around a backend, taking the rest from the environment.
    pub fn new(backend: Arc<dyn backend::Backend>) -> Self {
        AppState {
            backend,
            auth: Arc::new(middleware::Auth::from_env()),
            rate_limit: Arc::new(middleware::RateLimit::from_env()),
        }
    }
}
