//! The request and response bodies, from the resource schemas.
//!
//! Generated by firestone. Do not edit: change the resource files and regenerate.
//! A property firestone cannot name exactly, an embedded resource or a free form
//! object, is carried as `serde_json::Value` rather than guessed at.

use serde::Deserialize;
use serde::Serialize;

/// An example of an addressbook resource
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Addressbook {
    /// A unique identifier for an addressbook entry.
    #[serde(rename = "address_key")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub address_key: Option<String>,
    /// This is a person object that lives at this address.
    #[serde(rename = "person")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub person: Option<serde_json::Value>,
    /// The address type, e.g. work or home
    #[serde(rename = "addrtype")]
    pub addrtype: String,
    /// The street and civic number of this address
    #[serde(rename = "street")]
    pub street: String,
    /// The city of this address
    #[serde(rename = "city")]
    pub city: String,
    /// The state of this address
    #[serde(rename = "state")]
    pub state: String,
    /// The country of this address
    #[serde(rename = "country")]
    pub country: String,
    /// A list of people's names living there
    #[serde(rename = "people")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub people: Option<Vec<String>>,
    /// Address is valid or not
    #[serde(rename = "is_valid")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub is_valid: Option<bool>,
}

/// The query parameters accepted when listing addressbook.
#[derive(Clone, Debug, Default, Deserialize)]
pub struct AddressbookQuery {
    /// Limit the number of responses back
    #[serde(rename = "limit", default)]
    pub limit: Option<i64>,
    /// The offset to start returning resources
    #[serde(rename = "offset", default)]
    pub offset: Option<i64>,
    /// Filter by city name
    #[serde(rename = "city", default)]
    pub city: Option<String>,
}

/// An example of a persons resource
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Person {
    /// A UUID associated to this person
    #[serde(rename = "uuid")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub uuid: Option<String>,
    /// The person's first name
    #[serde(rename = "first_name")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub first_name: Option<String>,
    /// The person's last name
    #[serde(rename = "last_name")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub last_name: Option<String>,
    /// The person's age
    #[serde(rename = "age")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub age: Option<i64>,
    /// The person's hobbies
    #[serde(rename = "hobbies")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub hobbies: Option<Vec<String>>,
    /// The person's timezone (e.g. UTC, America/New_York)
    #[serde(rename = "timezone")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub timezone: Option<String>,
}

/// The query parameters accepted when listing persons.
#[derive(Clone, Debug, Default, Deserialize)]
pub struct PersonQuery {
    /// Limit the number of responses back
    #[serde(rename = "limit", default)]
    pub limit: Option<i64>,
    /// The offset to start returning resources
    #[serde(rename = "offset", default)]
    pub offset: Option<i64>,
    /// Filter by last name
    #[serde(rename = "last_name", default)]
    pub last_name: Option<String>,
}

/// An example of a postal code resource
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct PostalCode {
    /// A UUID associated to this postal code
    #[serde(rename = "uuid")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub uuid: Option<String>,
    /// The postal code's name/id
    #[serde(rename = "name")]
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
}

/// The query parameters accepted when listing postal_codes.
#[derive(Clone, Debug, Default, Deserialize)]
pub struct PostalCodeQuery {
    /// Limit the number of responses back
    #[serde(rename = "limit", default)]
    pub limit: Option<i64>,
    /// The offset to start returning resources
    #[serde(rename = "offset", default)]
    pub offset: Option<i64>,
    /// Filter by name
    #[serde(rename = "name", default)]
    pub name: Option<String>,
}
