//! The router, from the paths and methods in the resource schemas.
//!
//! Generated by firestone. Do not edit: change `methods` or `security` in the
//! resource files and regenerate.
//!
//! Adding your own middleware is a `.layer(...)` here, or a `.route_layer(...)` on
//! a single group if it should only cover some of the routes, the way the bearer
//! check below only covers the operations the schemas marked as secured.

use std::time::Duration;

use axum::http::StatusCode;
use axum::middleware;
use axum::routing::delete;
use axum::routing::get;
use axum::routing::post;
use axum::routing::put;
use axum::Router;
use tower_http::limit::RequestBodyLimitLayer;
use tower_http::timeout::TimeoutLayer;
use tower_http::trace::TraceLayer;

use crate::handlers;
use crate::AppState;

/// The largest request body this API will read, in bytes.
const MAX_BODY: usize = 1024 * 1024;

/// The longest a handler may take before the caller is given up on.
const TIMEOUT: Duration = Duration::from_secs(30);

/// Build the router for every resource firestone generated.
pub fn router(state: AppState) -> Router {
    let open = Router::new()
        // addressbook
        .route(
            "/addressbook",
            get(handlers::addressbook::get_collection).post(handlers::addressbook::post_collection),
        )
        .route(
            "/addressbook/{address_key}",
            get(handlers::addressbook::get_instance)
                .put(handlers::addressbook::put_instance)
                .delete(handlers::addressbook::delete_instance),
        )
        .route(
            "/addressbook/{address_key}/{attr}",
            get(handlers::addressbook::get_attr)
                .put(handlers::addressbook::put_attr)
                .delete(handlers::addressbook::delete_attr),
        )
        // persons
        .route("/persons", get(handlers::persons::get_collection))
        .route("/persons/{uuid}", get(handlers::persons::get_instance))
        // postal_codes
        .route("/postal_codes", get(handlers::postal_codes::get_collection))
        .route(
            "/postal_codes/{uuid}",
            get(handlers::postal_codes::get_instance),
        )
        .route(
            "/postal_codes/{uuid}/{attr}",
            get(handlers::postal_codes::get_attr),
        );

    // Only the operations the resource files marked as secured.
    let secured = Router::new()
        .route("/persons", post(handlers::persons::post_collection))
        .route(
            "/persons/{uuid}",
            put(handlers::persons::put_instance).delete(handlers::persons::delete_instance),
        )
        .route(
            "/postal_codes",
            post(handlers::postal_codes::post_collection),
        )
        .route(
            "/postal_codes/{uuid}",
            delete(handlers::postal_codes::delete_instance),
        )
        .route(
            "/postal_codes/{uuid}/{attr}",
            delete(handlers::postal_codes::delete_attr),
        )
        .route_layer(middleware::from_fn_with_state(
            state.clone(),
            crate::middleware::require_bearer,
        ));

    let routes = open.merge(secured);

    routes
        // Applied to everything, so a caller cannot avoid the limiter by picking an
        // unauthenticated route.
        .route_layer(middleware::from_fn_with_state(
            state.clone(),
            crate::middleware::rate_limit,
        ))
        .layer(TraceLayer::new_for_http())
        .layer(TimeoutLayer::with_status_code(
            StatusCode::GATEWAY_TIMEOUT,
            TIMEOUT,
        ))
        .layer(RequestBodyLimitLayer::new(MAX_BODY))
        .with_state(state)
}
