/*
 * Example person and addressbook API
 *
 * Example person and addressbook API
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Contact {
    /// Contact categories (array of enums)
    #[serde(rename = "categories", skip_serializing_if = "Option::is_none")]
    pub categories: Option<Vec<Categories>>,
    #[serde(
        rename = "contact_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub contact_id: Option<Option<serde_json::Value>>,
    /// Contact email address
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The contact's name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Optional notes (array of strings, not enums)
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Vec<String>>,
    /// Contact priority level (required enum)
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Priority>,
    /// The status of the contact (optional enum with default)
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// The contact type (optional enum, tests Rust keyword escaping)
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl Contact {
    pub fn new() -> Contact {
        Contact {
            categories: None,
            contact_id: None,
            email: None,
            name: None,
            notes: None,
            priority: None,
            status: None,
            r#type: None,
        }
    }
}
/// Contact categories (array of enums)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Categories {
    #[serde(rename = "family")]
    Family,
    #[serde(rename = "friend")]
    Friend,
    #[serde(rename = "colleague")]
    Colleague,
    #[serde(rename = "vendor")]
    Vendor,
}

impl Default for Categories {
    fn default() -> Categories {
        Self::Family
    }
}
/// Contact priority level (required enum)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Priority {
    #[serde(rename = "high")]
    High,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "low")]
    Low,
}

impl Default for Priority {
    fn default() -> Priority {
        Self::High
    }
}
/// The status of the contact (optional enum with default)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "archived")]
    Archived,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}
/// The contact type (optional enum, tests Rust keyword escaping)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "personal")]
    Personal,
    #[serde(rename = "business")]
    Business,
    #[serde(rename = "emergency")]
    Emergency,
}

impl Default for Type {
    fn default() -> Type {
        Self::Personal
    }
}
