/*
 * Example person and addressbook API
 *
 * Example person and addressbook API
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePerson {
    /// The person's age
    #[serde(rename = "age", skip_serializing_if = "Option::is_none")]
    pub age: Option<i32>,
    /// The person's first name
    #[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// The person's hobbies
    #[serde(rename = "hobbies", skip_serializing_if = "Option::is_none")]
    pub hobbies: Option<Vec<String>>,
    /// The person's last name
    #[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(
        rename = "uuid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub uuid: Option<Option<serde_json::Value>>,
}

impl CreatePerson {
    pub fn new() -> CreatePerson {
        CreatePerson {
            age: None,
            first_name: None,
            hobbies: None,
            last_name: None,
            uuid: None,
        }
    }
}
