/*
 * Example person and addressbook API
 *
 * Example person and addressbook API
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAddressbook {
    #[serde(
        rename = "address_key",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub address_key: Option<Option<serde_json::Value>>,
    /// The address type, e.g. work or home
    #[serde(rename = "addrtype")]
    pub addrtype: Addrtype,
    /// The city of this address
    #[serde(rename = "city")]
    pub city: String,
    /// The country of this address
    #[serde(rename = "country")]
    pub country: String,
    /// Address is valid or not
    #[serde(rename = "is_valid", skip_serializing_if = "Option::is_none")]
    pub is_valid: Option<bool>,
    /// A list of people's names living there
    #[serde(rename = "people", skip_serializing_if = "Option::is_none")]
    pub people: Option<Vec<String>>,
    #[serde(rename = "person", skip_serializing_if = "Option::is_none")]
    pub person: Option<Box<models::Person>>,
    /// The state of this address
    #[serde(rename = "state")]
    pub state: String,
    /// The street and civic number of this address
    #[serde(rename = "street")]
    pub street: String,
}

impl CreateAddressbook {
    pub fn new(
        addrtype: Addrtype,
        city: String,
        country: String,
        state: String,
        street: String,
    ) -> CreateAddressbook {
        CreateAddressbook {
            address_key: None,
            addrtype,
            city,
            country,
            is_valid: None,
            people: None,
            person: None,
            state,
            street,
        }
    }
}
/// The address type, e.g. work or home
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Addrtype {
    #[serde(rename = "work")]
    Work,
    #[serde(rename = "home")]
    Home,
}

impl Default for Addrtype {
    fn default() -> Addrtype {
        Self::Work
    }
}
