/*
 * Example person and addressbook API
 *
 * Example person and addressbook API
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContact {
    /// Contact categories (array of enums)
    #[serde(rename = "categories")]
    pub categories: Vec<Categories>,
    #[serde(rename = "contact_id", deserialize_with = "Option::deserialize")]
    pub contact_id: Option<serde_json::Value>,
    /// Contact email address
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The contact's name
    #[serde(rename = "name")]
    pub name: String,
    /// Optional notes (array of strings, not enums)
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Vec<String>>,
    /// Contact priority level (required enum)
    #[serde(rename = "priority")]
    pub priority: Priority,
    /// The status of the contact (optional enum with default)
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// The contact type (optional enum, tests Rust keyword escaping)
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl CreateContact {
    pub fn new(
        categories: Vec<Categories>,
        contact_id: Option<serde_json::Value>,
        name: String,
        priority: Priority,
    ) -> CreateContact {
        CreateContact {
            categories,
            contact_id,
            email: None,
            name,
            notes: None,
            priority,
            status: None,
            r#type: None,
        }
    }
}
/// Contact categories (array of enums)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Categories {
    #[serde(rename = "family")]
    Family,
    #[serde(rename = "friend")]
    Friend,
    #[serde(rename = "colleague")]
    Colleague,
    #[serde(rename = "vendor")]
    Vendor,
}

impl Default for Categories {
    fn default() -> Categories {
        Self::Family
    }
}
/// Contact priority level (required enum)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Priority {
    #[serde(rename = "high")]
    High,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "low")]
    Low,
}

impl Default for Priority {
    fn default() -> Priority {
        Self::High
    }
}
/// The status of the contact (optional enum with default)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "archived")]
    Archived,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}
/// The contact type (optional enum, tests Rust keyword escaping)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "personal")]
    Personal,
    #[serde(rename = "business")]
    Business,
    #[serde(rename = "emergency")]
    Emergency,
}

impl Default for Type {
    fn default() -> Type {
        Self::Personal
    }
}
