# coding: utf-8

"""
Example person and addressbook API

Example person and addressbook API

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from addressbook.apis.addressbook_api import router as AddressbookApiRouter
from addressbook.apis.persons_api import router as PersonsApiRouter
from addressbook.apis.postal_codes_api import router as PostalCodesApiRouter

app = FastAPI(
    title="Example person and addressbook API",
    description="Example person and addressbook API",
    version="1.0",
)

app.include_router(AddressbookApiRouter)
app.include_router(PersonsApiRouter)
app.include_router(PostalCodesApiRouter)
