//! Smoke tests for the generated routes.
//!
//! Generated by firestone from the same resource files as the router, so a route
//! that stops being reachable, or an unsecured route that should have been secured,
//! fails here. The app is driven directly rather than over a socket, so nothing
//! binds a port.

use std::sync::Arc;

use axum::body::Body;
use axum::http::Request;
use axum::http::StatusCode;
use tower::ServiceExt;

use addressbook_server::backend::InMemory;
use addressbook_server::middleware::Auth;
use addressbook_server::middleware::RateLimit;
use addressbook_server::router;
use addressbook_server::AppState;

/// A server with nothing stored and one accepted token.
fn app() -> axum::Router {
    let mut state = AppState::new(Arc::new(InMemory::new()));
    state.auth = Arc::new(Auth::new(["test-token".to_string()]));
    state.rate_limit = Arc::new(RateLimit::new(10_000, std::time::Duration::from_secs(60)));

    router(state)
}

async fn call(method: &str, path: &str, token: Option<&str>) -> StatusCode {
    let mut request = Request::builder().method(method).uri(path);
    if let Some(token) = token {
        request = request.header("authorization", format!("Bearer {token}"));
    }

    app()
        .oneshot(request.body(Body::empty()).expect("the request builds"))
        .await
        .expect("the router answers")
        .status()
}

#[tokio::test]
async fn addressbook_collection_is_reachable() {
    assert_eq!(call("GET", "/addressbook", None).await, StatusCode::OK);
}

#[tokio::test]
async fn addressbook_instance_is_not_found_when_absent() {
    assert_eq!(
        call("GET", "/addressbook/nope", None).await,
        StatusCode::NOT_FOUND
    );
}

#[tokio::test]
async fn addressbook_attribute_is_routed() {
    // The instance is absent, so a 404 rather than a 405 says the route matched.
    assert_eq!(
        call("GET", "/addressbook/nope/person", None).await,
        StatusCode::NOT_FOUND
    );
}

#[tokio::test]
async fn addressbook_head_is_answered_on_an_attribute() {
    // axum answers HEAD wherever GET is routed, which is what the schema's `head`
    // on an attribute asks for.
    assert_eq!(
        call("HEAD", "/addressbook/nope/person", None).await,
        StatusCode::NOT_FOUND
    );
}

#[tokio::test]
async fn persons_collection_is_reachable() {
    assert_eq!(call("GET", "/persons", None).await, StatusCode::OK);
}

#[tokio::test]
async fn persons_instance_is_not_found_when_absent() {
    assert_eq!(
        call("GET", "/persons/nope", None).await,
        StatusCode::NOT_FOUND
    );
}

#[tokio::test]
async fn persons_delete_instance_needs_a_token() {
    assert_eq!(
        call("DELETE", "/persons/anything", None).await,
        StatusCode::UNAUTHORIZED
    );
    assert_ne!(
        call("DELETE", "/persons/anything", Some("test-token")).await,
        StatusCode::UNAUTHORIZED
    );
}

#[tokio::test]
async fn persons_put_instance_needs_a_token() {
    assert_eq!(
        call("PUT", "/persons/anything", None).await,
        StatusCode::UNAUTHORIZED
    );
    assert_ne!(
        call("PUT", "/persons/anything", Some("test-token")).await,
        StatusCode::UNAUTHORIZED
    );
}

#[tokio::test]
async fn postal_codes_collection_is_reachable() {
    assert_eq!(call("GET", "/postal_codes", None).await, StatusCode::OK);
}

#[tokio::test]
async fn postal_codes_instance_is_not_found_when_absent() {
    assert_eq!(
        call("GET", "/postal_codes/nope", None).await,
        StatusCode::NOT_FOUND
    );
}

#[tokio::test]
async fn postal_codes_attribute_is_routed() {
    // The instance is absent, so a 404 rather than a 405 says the route matched.
    assert_eq!(
        call("GET", "/postal_codes/nope/name", None).await,
        StatusCode::NOT_FOUND
    );
}

#[tokio::test]
async fn postal_codes_head_is_answered_on_an_attribute() {
    // axum answers HEAD wherever GET is routed, which is what the schema's `head`
    // on an attribute asks for.
    assert_eq!(
        call("HEAD", "/postal_codes/nope/name", None).await,
        StatusCode::NOT_FOUND
    );
}

#[tokio::test]
async fn postal_codes_delete_instance_needs_a_token() {
    assert_eq!(
        call("DELETE", "/postal_codes/anything", None).await,
        StatusCode::UNAUTHORIZED
    );
    assert_ne!(
        call("DELETE", "/postal_codes/anything", Some("test-token")).await,
        StatusCode::UNAUTHORIZED
    );
}

#[tokio::test]
async fn an_unknown_route_is_not_found() {
    assert_eq!(
        call("GET", "/no-such-resource", None).await,
        StatusCode::NOT_FOUND
    );
}
