kind: persons
apiVersion: v1
versionInPath: false
metadata:
  description: An example of a persons resource
default_query_params:
  - name: limit
    description: Limit the number of responses back
    in: query
    schema:
      type: integer
  - name: offset
    description: The offset to start returning resources
    in: query
    schema:
      type: integer
descriptions:
  resource:
    get: List all persons in this collection
    head: Determine the existence and size of persons in this collection
    patch: Patch one or more persons in this collection
    post: Create a new person in this collection, a new UUID key will be created
  instance:
    get: Get a specific person from this collection
    head: Determine the existence and size of this person
    patch: Patch this person in the collection
    put: Put a new person in this collection, with the given UUId key
methods:
  resource:
    - get
    - post
  instance:
    - delete
    - get
    - head
    - put
  instance_attrs: []
#   - delete
#   - get
#   - head
#   - put
security:
  scheme:
    bearer_auth:
      scheme: bearer
      type: http
      bearerFormat: JWT
  resource:
    - post
  instance:
    - delete
    - put
  instance_attrs: []
#   - delete
#   - put
schema:
  type: array
  key:
    name: uuid
    description: A UUID associated to this person
    schema:
      type: string
  query_params:
    - name: last_name
      description: Filter by last name
      schema:
        type: string
      methods:
        - get
  items:
    type: object
    properties:
      uuid:
        expose: false
        description: A UUID associated to this person
        schema:
          type: string
      first_name:
        description: The person's first name
        type: string
        # Don't expose this attribute in the URL/specification
        # expose: false
      last_name:
        description: The person's last name
        type: string
      age:
        description: The person's age
        type: integer
      hobbies:
        description: The person's hobbies
        type: array
        items:
          type: string
