"""
Declarative validations for this API.

Generated by firestone from the ``references`` and ``validations`` blocks in the
resource schemas.  Rules are data, in ``rules.py``; the engine is in
``runtime.py``; the interface you implement is in ``ports.py``.

Typical use, from a server handler::

    from myapi.validation import ValidationError, validate

    try:
        await validate("post", "addressbook", body, resolver=my_resolver)
    except ValidationError as exc:
        return JSONResponse(
            status_code=exc.status,
            content=exc.to_problem(),
            media_type="application/problem+json",
        )

Return the response rather than raising ``HTTPException``: that would nest the
problem under a ``detail`` key and send ``application/json``, which is neither the
shape nor the media type the generated OpenAPI document declares. Registering an
exception handler for ``ValidationError`` on the app does this once for every route.
"""

from .ports import MISSING
from .ports import RefRequest
from .ports import Resolver
from .ports import RuleEvaluationError
from .ports import ValidationError
from .ports import Violation
from .rules import RULES
from .runtime import validate_with_rules

__all__ = [
    "MISSING",
    "RULES",
    "RefRequest",
    "Resolver",
    "RuleEvaluationError",
    "ValidationError",
    "Violation",
    "validate",
    "validate_with_rules",
]


async def validate(op, resource, body=None, old=None, resolver=None, ctx=None, subject=None):
    """Run every generated rule that applies to this operation.

    :param str op: the HTTP method being performed, e.g. ``post``
    :param str resource: the resource kind being operated on, e.g. ``addressbook``
    :param body: the request body, a dict or a pydantic model
    :param old: the resource as it currently stands, needed by PATCH, PUT and DELETE rules
    :param resolver: an object implementing :class:`~.ports.Resolver`
    :param dict ctx: request scoped context, read by the rules and handed to the
        resolver: the caller's roles, the tenant, a trace id. Must be JSON serialisable.
    :param dict subject: the resource as it will be once this request succeeds, when
        you would rather work that out yourself than have ``body`` merged over ``old``
    :raises ValidationError: if one or more rules failed
    """
    return await validate_with_rules(
        RULES, op, resource, body=body, old=old, resolver=resolver, ctx=ctx, subject=subject
    )
