"""
The interfaces of the validation package.

This file is generated by firestone but never changes: it is the contract
between the generated rules and your application.  The only thing you have to
write is a :class:`Resolver`.
"""

import dataclasses
import typing


class _Missing:
    """A value that is absent, as distinct from a value that is null."""

    def __repr__(self):
        return "MISSING"

    def __bool__(self):
        return False


#: Returned by path lookups when a field is not present at all.
MISSING = _Missing()


@dataclasses.dataclass(frozen=True)
class RefRequest:
    """A single lookup a rule needs before it can be evaluated.

    :param str kind: the resource kind to look up, e.g. ``persons``
    :param str key: the attribute of that resource to match on, e.g. ``first_name``
    :param value: the value to match, taken from the request body
    """

    kind: str
    key: str
    value: typing.Any

    @property
    def id(self) -> str:
        """A stable identifier for this lookup, used to key the resolved results."""
        return f"{self.kind}/{self.key}/{self.value!r}"


#: What ``resolve`` returns, whether it is a coroutine function or a plain one.
Resolved = typing.Mapping[str, typing.Any]
MaybeAwaitable = typing.Union[Resolved, typing.Awaitable[Resolved]]


@typing.runtime_checkable
class Resolver(typing.Protocol):
    """Fetches the resources that validation rules depend on.

    Implement this against whatever you already have: a database, an ORM, a
    cache, another service.  Firestone works out *what* needs fetching; this is
    the only place that knows *how*.

    ``resolve`` may be a coroutine or a plain function.  It is handed every
    lookup needed by a single request at once, already de-duplicated, so a
    request that touches ten rules still costs one round trip.
    """

    def resolve(
        self, requests: typing.Sequence[RefRequest], ctx: typing.Mapping[str, typing.Any]
    ) -> MaybeAwaitable:
        """Resolve the given lookups.

        :param requests: the lookups to perform, de-duplicated
        :param ctx: the read-only request context passed to ``validate``, for
            whatever scoping a lookup needs: the tenant, the caller's authorisation
            scope, a trace id.  Rules can read it too, so it has to be JSON
            serialisable; a database session or transaction belongs on the resolver
            instance rather than in here.
        :return: a mapping of :attr:`RefRequest.id` to the resource found.
            Omit the entry, or map it to ``None``, for anything that does not exist.
        """


@dataclasses.dataclass(frozen=True)
class Violation:
    """A single rule that failed."""

    rule: str
    resource: str
    field: typing.Optional[str]
    message: str
    status: int

    def as_dict(self) -> dict:
        """Get this violation in the shape used by the problem document."""
        violation = {
            "rule": self.rule,
            "resource": self.resource,
            "message": self.message,
        }
        if self.field:
            violation["field"] = self.field

        return violation


class ValidationError(Exception):
    """One or more validation rules failed.

    :param violations: every rule that failed for this request
    """

    def __init__(self, violations: typing.Sequence[Violation]):
        self.violations = list(violations)
        super().__init__("; ".join(violation.message for violation in self.violations))

    @property
    def status(self) -> int:
        """The status code to respond with, the highest of any violation's."""
        return max(violation.status for violation in self.violations)

    def to_problem(self) -> dict:
        """Get an RFC 9457 problem detail describing every violation."""
        return {
            "type": "about:blank",
            "title": "Validation failed",
            "status": self.status,
            "detail": self.violations[0].message,
            "violations": [violation.as_dict() for violation in self.violations],
        }


class RuleEvaluationError(Exception):
    """A rule could not be evaluated at all, as opposed to failing.

    This is a bug in the rule or in the data it was given, not a rejected
    request, and should surface as a 500 rather than a validation failure.
    """
