"""
The validation rules for this API.

Generated by firestone. Do not edit: change the ``references`` and
``validations`` blocks in your resource schemas and regenerate.

Some of these rules carry a CEL expression, so this package needs ``cel-python``
at runtime::

    pip install cel-python
"""

#: Every rule, keyed by the resource kind it applies to.
RULES = {
    "addressbook": [
        {
            "name": "person_must_exist",
            "description": "The referenced persons must already exist.",
            "resource": "addressbook",
            "kind": "exists",
            "field": "person.first_name",
            "methods": [
                "post",
                "put",
                "patch",
            ],
            "refs": [
                {
                    "name": "person",
                    "kind": "persons",
                    "key": "first_name",
                    "value": "person.first_name",
                    "optional": False,
                },
            ],
            "expr": None,
            "error": {
                "status": 422,
                "message": "No persons found with first_name '{self.person.first_name}'.",
            },
            "examples": [],
        },
        {
            "name": "only_admins_may_invalidate",
            "description": "Marking an address invalid is an administrative action.",
            "resource": "addressbook",
            "kind": "expr",
            "field": None,
            "methods": [
                "put",
                "patch",
            ],
            "refs": [],
            "expr": 'self.is_valid == old.is_valid || (has(ctx.roles) && "admin" in ctx.roles)',
            "error": {
                "status": 403,
                "message": "Only an admin may change is_valid on an address.",
            },
            "examples": [
                {
                    "self": {
                        "is_valid": False,
                    },
                    "old": {
                        "is_valid": True,
                    },
                    "refs": {},
                    "ctx": {
                        "roles": [
                            "admin",
                        ],
                    },
                    "expect": "pass",
                },
                {
                    "self": {
                        "is_valid": False,
                    },
                    "old": {
                        "is_valid": True,
                    },
                    "refs": {},
                    "ctx": {
                        "roles": [
                            "user",
                        ],
                    },
                    "expect": "fail",
                },
                {
                    "self": {
                        "is_valid": True,
                    },
                    "old": {
                        "is_valid": True,
                    },
                    "refs": {},
                    "ctx": {
                        "roles": [
                            "user",
                        ],
                    },
                    "expect": "pass",
                },
            ],
        },
    ],
    "persons": [
        {
            "name": "person_is_not_in_use",
            "description": "A person cannot be deleted while an address still points at them.",
            "resource": "persons",
            "kind": "expr",
            "field": None,
            "methods": [
                "delete",
            ],
            "refs": [
                {
                    "name": "address",
                    "kind": "addressbook",
                    "key": "person.first_name",
                    "value": "first_name",
                    "optional": True,
                },
            ],
            "expr": "!has(refs.address)",
            "error": {
                "status": 409,
                "message": "{self.first_name} still has an address in the addressbook.",
            },
            "examples": [
                {
                    "self": {
                        "first_name": "Ann",
                    },
                    "old": None,
                    "refs": {},
                    "ctx": {},
                    "expect": "pass",
                },
                {
                    "self": {
                        "first_name": "Bob",
                    },
                    "old": None,
                    "refs": {
                        "address": {
                            "address_key": "bob-home",
                        },
                    },
                    "ctx": {},
                    "expect": "fail",
                },
            ],
        },
    ],
}
