"""
The validation engine.

This file is generated by firestone but never changes: all of the per-project
detail lives in ``rules.py``.  It has no dependency on firestone, and imports
``celpy`` only when a rule carrying an expression is actually evaluated.
"""

import inspect
import logging
import re
import types

from .ports import MISSING
from .ports import RefRequest
from .ports import RuleEvaluationError
from .ports import ValidationError
from .ports import Violation

_LOGGER = logging.getLogger(__name__)

_PLACEHOLDER = re.compile(r"\{([a-zA-Z_][a-zA-Z0-9_.]*)\}")
_PROGRAMS = {}


def _as_dict(obj) -> dict:
    """Coerce a request body to a plain dict, pydantic models included."""
    if obj is None:
        return {}
    if isinstance(obj, dict):
        return obj
    if hasattr(obj, "model_dump"):
        return obj.model_dump(mode="json", exclude_unset=True)
    if hasattr(obj, "dict"):
        return obj.dict(exclude_unset=True)

    raise RuleEvaluationError(f"Cannot validate a {type(obj).__name__}, expected a mapping")


def resolve_path(data, path: str):
    """Look up a dotted path such as ``person.first_name``.

    :return: the value found, or ``MISSING`` if any part of the path is absent
    """
    current = data
    for part in path.split("."):
        if isinstance(current, dict):
            if part not in current:
                return MISSING
            current = current[part]
        elif hasattr(current, part):
            current = getattr(current, part)
        else:
            return MISSING

        if current is MISSING:
            return MISSING

    return current


def _format(message: str, scope: dict) -> str:
    """Interpolate ``{self.city}`` style placeholders in an error message."""

    def replace(match):
        value = resolve_path(scope, match.group(1))
        return match.group(0) if value is MISSING else str(value)

    return _PLACEHOLDER.sub(replace, message)


def _merge(old: dict, body: dict) -> dict:
    """Apply a partial body over the current resource, nested objects included.

    Nested objects are merged, so a body that touches one field of an embedded
    object leaves the rest of that object alone.  Everything else is replaced
    outright: lists wholesale, and an explicit null as a null rather than as a
    removal.  That last point is where this differs from RFC 7386 JSON Merge
    Patch, which deletes a member set to null.

    If your API implements merge patch properly, or JSON Patch, or anything else,
    do not rely on this: work out the resulting document yourself and hand it to
    ``validate`` as ``subject``.
    """
    merged = dict(old)
    for key, value in body.items():
        current = merged.get(key)
        merged[key] = _merge(current, value) if _is_mapping(current, value) else value

    return merged


def _is_mapping(current, value) -> bool:
    """Whether both sides of an update are objects, and so should be merged."""
    return isinstance(current, dict) and isinstance(value, dict)


def _subject(op: str, body, old) -> dict:
    """Get the object the rules are evaluated against.

    A PATCH is validated against the state the resource would end up in, so a
    partial body is merged over the current one.  A DELETE has no body, so it is
    validated against the resource being deleted.
    """
    body = _as_dict(body)
    old = _as_dict(old)
    if op == "delete":
        return old or body
    if op == "patch" and old:
        return _merge(old, body)

    return body


def _evaluate_expr(rule: dict, scope: dict) -> bool:
    """Evaluate a rule's CEL expression against the given scope."""
    try:
        # pylint: disable=import-outside-toplevel
        import celpy
    except ImportError as exc:
        raise RuleEvaluationError(
            f"Rule '{rule['name']}' needs CEL support; install it with 'pip install cel-python'"
        ) from exc

    expr = rule["expr"]
    program = _PROGRAMS.get(expr)
    if program is None:
        env = celpy.Environment()
        try:
            program = env.program(env.compile(expr))
        except Exception as exc:
            raise RuleEvaluationError(
                f"Rule '{rule['name']}' has an invalid CEL expression: {exc}"
            ) from exc
        _PROGRAMS[expr] = program

    try:
        result = program.evaluate(celpy.json_to_cel(scope))
    except Exception as exc:
        raise RuleEvaluationError(f"Rule '{rule['name']}' could not be evaluated: {exc}") from exc

    return bool(result)


def _unresolved(rule: dict, refs: dict):
    """Get the first lookup this rule needed but did not get, if any.

    A rule that reads through a lookup cannot be evaluated when that lookup found
    nothing, so rather than let the expression blow up, the rule simply fails. A
    rule that is *about* absence declares its lookup ``optional`` and guards the
    expression with ``has()``.
    """
    for ref in rule["refs"]:
        if not ref["optional"] and ref["name"] not in refs:
            return ref

    return None


def _missing_violation(rule: dict, ref: dict, subject: dict) -> Violation:
    """Report a required lookup that found nothing, in terms of the lookup itself."""
    value = resolve_path(subject, ref["value"])
    return Violation(
        rule=rule["name"],
        resource=rule["resource"],
        field=rule["field"] or ref["value"],
        message=f"No {ref['kind']} found with {ref['key']} '{value}'.",
        status=rule["error"]["status"],
    )


def _passes(rule: dict, scope: dict) -> bool:
    """Evaluate a single rule that has had all of its lookups resolved."""
    kind = rule["kind"]
    if kind == "exists":
        # Its lookup is required, so reaching here means the resource was found.
        return True
    if kind == "immutable":
        if not scope["old"]:
            return True
        return resolve_path(scope["old"], rule["field"]) == resolve_path(
            scope["self"], rule["field"]
        )
    if kind == "expr":
        return _evaluate_expr(rule, scope)

    raise RuleEvaluationError(f"Rule '{rule['name']}' has an unknown kind '{kind}'")


def _unchanged(rule: dict, subject: dict, old: dict) -> bool:
    """Whether an existence rule is checking a reference that did not change.

    A reference that is the same as the one already stored was checked when it was
    stored, so an update that leaves it alone does not need to look it up again.
    """
    if rule["kind"] != "exists" or not old:
        return False

    return all(
        resolve_path(old, ref["value"]) == resolve_path(subject, ref["value"])
        for ref in rule["refs"]
    )


def _plan(rules: list, subject: dict, old: dict):
    """Work out every lookup the given rules need.

    A rule whose lookup value is not present in the subject is skipped rather
    than failed, so a PATCH that does not touch a referenced field is left alone.

    :return: the runnable rules paired with their lookups, and the de-duplicated requests
    """
    requests = {}
    runnable = []

    for rule in rules:
        if _unchanged(rule, subject, old):
            _LOGGER.debug(f"Skipping rule '{rule['name']}': the reference did not change")
            continue

        plan = {}
        for ref in rule["refs"]:
            value = resolve_path(subject, ref["value"])
            if value is MISSING or value is None:
                _LOGGER.debug(
                    f"Skipping rule '{rule['name']}': {ref['value']} is not in the request"
                )
                plan = None
                break
            request = RefRequest(kind=ref["kind"], key=ref["key"], value=value)
            requests.setdefault(request.id, request)
            plan[ref["name"]] = request.id

        if plan is not None:
            runnable.append((rule, plan))

    return runnable, list(requests.values())


async def validate_with_rules(
    rules: dict,
    op: str,
    resource: str,
    body=None,
    old=None,
    resolver=None,
    ctx: dict = None,
    subject: dict = None,
):
    """Run every rule that applies to this operation.

    :param dict rules: the rules to run, keyed by resource kind
    :param str op: the HTTP method being performed, e.g. ``post``
    :param str resource: the resource kind being operated on, e.g. ``addressbook``
    :param body: the request body, a dict or a pydantic model
    :param old: the resource as it currently stands, needed by PATCH, PUT and DELETE rules
    :param resolver: an object implementing :class:`~.ports.Resolver`
    :param dict ctx: request scoped context, read by the rules and handed to the
        resolver: the caller's roles, the tenant, a trace id. Must be JSON
        serialisable, since rules can read it.
    :param dict subject: the resource as it will be once this request succeeds,
        when you would rather work that out yourself than have ``body`` merged over
        ``old``. Needed for anything whose update semantics are not a plain merge,
        and for endpoints that update one attribute rather than a whole resource.
    :raises ValidationError: if one or more rules failed
    :raises RuleEvaluationError: if a rule could not be evaluated at all
    """
    op = op.lower()
    applicable = [rule for rule in rules.get(resource, []) if op in rule["methods"]]
    if not applicable:
        return

    ctx = dict(ctx or {})
    subject = _as_dict(subject) if subject is not None else _subject(op, body, old)
    runnable, requests = _plan(applicable, subject, _as_dict(old))

    resolved = {}
    if requests:
        if resolver is None:
            raise RuleEvaluationError(
                f"Validating {op} on {resource} needs {len(requests)} lookup(s) "
                "but no resolver was given"
            )
        _LOGGER.debug(f"Resolving {len(requests)} lookup(s) for {op} on {resource}")
        resolved = resolver.resolve(requests, types.MappingProxyType(ctx))
        if inspect.isawaitable(resolved):
            resolved = await resolved
        resolved = dict(resolved or {})

    violations = []
    for rule, plan in runnable:
        refs = {name: resolved.get(request_id) for name, request_id in plan.items()}
        scope = {
            "self": subject,
            "old": _as_dict(old),
            "ctx": ctx,
            "refs": {name: ref for name, ref in refs.items() if ref is not None},
        }

        unresolved = _unresolved(rule, scope["refs"])
        if unresolved is not None:
            violations.append(_missing_violation(rule, unresolved, subject))
            continue

        if _passes(rule, scope):
            continue

        _LOGGER.info(f"Validation rule '{rule['name']}' failed for {op} on {resource}")
        violations.append(
            Violation(
                rule=rule["name"],
                resource=rule["resource"],
                field=rule["field"],
                message=_format(rule["error"]["message"], scope),
                status=rule["error"]["status"],
            )
        )

    if violations:
        raise ValidationError(violations)
