"""
Tests for the validation rules, generated from the examples in the resource schemas.

Generated by firestone. Do not edit: add or change ``examples`` on a rule and
regenerate.  The rules run against an in-memory resolver, so no database, and no
server, is needed.
"""

import asyncio

import pytest

from .ports import ValidationError
from .rules import RULES
from .runtime import validate_with_rules

#: One entry per example: the resource, the rule, the method to run it on, and the example.
EXAMPLES = [
    [
        "addressbook",
        "only_admins_may_invalidate",
        "put",
        {
            "self": {
                "is_valid": False,
            },
            "old": {
                "is_valid": True,
            },
            "refs": {},
            "ctx": {
                "roles": [
                    "admin",
                ],
            },
            "expect": "pass",
        },
    ],
    [
        "addressbook",
        "only_admins_may_invalidate",
        "put",
        {
            "self": {
                "is_valid": False,
            },
            "old": {
                "is_valid": True,
            },
            "refs": {},
            "ctx": {
                "roles": [
                    "user",
                ],
            },
            "expect": "fail",
        },
    ],
    [
        "addressbook",
        "only_admins_may_invalidate",
        "put",
        {
            "self": {
                "is_valid": True,
            },
            "old": {
                "is_valid": True,
            },
            "refs": {},
            "ctx": {
                "roles": [
                    "user",
                ],
            },
            "expect": "pass",
        },
    ],
    [
        "persons",
        "person_is_not_in_use",
        "delete",
        {
            "self": {
                "first_name": "Ann",
            },
            "old": None,
            "refs": {},
            "ctx": {},
            "expect": "pass",
        },
    ],
    [
        "persons",
        "person_is_not_in_use",
        "delete",
        {
            "self": {
                "first_name": "Bob",
            },
            "old": None,
            "refs": {
                "address": {
                    "address_key": "bob-home",
                },
            },
            "ctx": {},
            "expect": "fail",
        },
    ],
]

IDS = [f"{resource}-{name}-{index}" for index, (resource, name, _, _) in enumerate(EXAMPLES)]


class FakeResolver:
    """Returns the resources an example declares, instead of hitting a database."""

    def __init__(self, rule: dict, refs: dict):
        self.rule = rule
        self.refs = refs

    def resolve(self, requests, ctx):
        """Match each request back to the named ref the example provided."""
        del ctx  # an example declares what is found, so nothing here is scoped
        resolved = {}
        for request in requests:
            for ref in self.rule["refs"]:
                if ref["kind"] != request.kind or ref["key"] != request.key:
                    continue
                found = self.refs.get(ref["name"])
                if found is not None:
                    resolved[request.id] = found

        return resolved


def get_rule(resource: str, name: str) -> dict:
    """Get a single rule by resource kind and rule name."""
    for rule in RULES[resource]:
        if rule["name"] == name:
            return rule

    raise AssertionError(f"No rule named '{name}' on {resource}")


@pytest.mark.parametrize("resource,name,op,example", EXAMPLES, ids=IDS)
def test_rule_example(resource, name, op, example):
    """Check that a rule accepts or rejects its example as the schema says it should."""
    rule = get_rule(resource, name)

    def run():
        return asyncio.run(
            validate_with_rules(
                {resource: [rule]},
                op,
                resource,
                body=example["self"],
                old=example["old"],
                resolver=FakeResolver(rule, example["refs"]),
                ctx=example["ctx"],
            )
        )

    if example["expect"] == "pass":
        run()
        return

    with pytest.raises(ValidationError) as excinfo:
        run()
    assert excinfo.value.violations[0].rule == name
